import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

type Seed = {
  title: string;
  description: string;
  category: string;
  borough: string;
  venue: string;
  address: string;
  lat: number;
  lng: number;
  ageMin: number;
  ageMax: number;
  isFree: boolean;
  priceMin: number;
  priceMax: number;
  startDate: string;
  endDate: string;
  times?: string;
  sourceName: string;
  sourceUrl: string;
};

const activities: Seed[] = [
  {
    title: "Summer Holiday Family Activities at IWM London",
    description:
      "Free daily drop-in activities in the Clore Learning Centre and galleries, including building paper houses for the 'What Makes a Home?' trail and the Childhood in War stamp trail exploring young people's wartime experiences.",
    category: "Museum & Heritage",
    borough: "Lambeth",
    venue: "Imperial War Museum London",
    address: "Lambeth Road, London SE1 6HZ",
    lat: 51.4959,
    lng: -0.1092,
    ageMin: 4,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-22",
    endDate: "2026-08-23",
    times: "Daily, 10am - 4pm",
    sourceName: "Imperial War Museums",
    sourceUrl: "https://www.iwm.org.uk/events/family-activities-iwm-london",
  },
  {
    title: "October Half Term Holiday Club - Herne Hill Velodrome",
    description:
      "Track cycling and mountain biking holiday club for young riders of all abilities, with bikes and helmets available to hire and a one-hour lunch break included.",
    category: "Sports",
    borough: "Southwark",
    venue: "Herne Hill Velodrome",
    address: "104 Burbage Road, London SE24 9HE",
    lat: 51.4568,
    lng: -0.1024,
    ageMin: 8,
    ageMax: 16,
    isFree: false,
    priceMin: 10,
    priceMax: 15,
    startDate: "2026-10-19",
    endDate: "2026-10-23",
    times: "Weekdays, 10am - 3pm",
    sourceName: "Herne Hill Velodrome",
    sourceUrl: "https://www.hernehillvelodrome.com/holiday-clubs",
  },
  {
    title: "Family Visit & Pirate Training Experience at the Golden Hinde",
    description:
      "Climb aboard a full-size replica of Sir Francis Drake's Tudor galleon for a self-guided or costumed-guide tour, with a pirate-themed training session available for children aged 7 and up.",
    category: "Museum & Heritage",
    borough: "Southwark",
    venue: "The Golden Hinde",
    address: "St Mary Overie Dock, Cathedral Street, London SE1 9DE",
    lat: 51.5062,
    lng: -0.0912,
    ageMin: 5,
    ageMax: 12,
    isFree: false,
    priceMin: 6,
    priceMax: 20,
    startDate: "2026-07-27",
    endDate: "2026-09-06",
    times: "Daily, 10am - 6pm",
    sourceName: "The Golden Hinde",
    sourceUrl: "https://www.goldenhinde.co.uk/",
  },
  {
    title: "Farm Club Summer Sessions at Surrey Docks Farm",
    description:
      "Full-day sessions for children where they take part in animal care such as mucking out pens and small-animal handling, plus nature crafts, bushcraft and pond dipping on a working city farm.",
    category: "Nature",
    borough: "Southwark",
    venue: "Surrey Docks Farm",
    address: "South Wharf, Rotherhithe Street, London SE16 5ET",
    lat: 51.4967,
    lng: -0.0448,
    ageMin: 8,
    ageMax: 13,
    isFree: false,
    priceMin: 42,
    priceMax: 42,
    startDate: "2026-08-05",
    endDate: "2026-08-19",
    times: "Select dates, 10am - 4pm",
    sourceName: "Surrey Docks Farm",
    sourceUrl: "https://surreydocksfarm.org.uk/farm-club/",
  },
  {
    title: "Summer Holiday Mini Tennis Camps at Southwark Park",
    description:
      "Professionally coached tennis camps combining skill drills, games and friendly competition for young players, run on the outdoor courts in Southwark Park.",
    category: "Sports",
    borough: "Southwark",
    venue: "Southwark Park Tennis Courts",
    address: "Southwark Park, Jamaica Road, London SE16 2TX",
    lat: 51.4955,
    lng: -0.0526,
    ageMin: 5,
    ageMax: 9,
    isFree: false,
    priceMin: 20,
    priceMax: 20,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times: "Weekdays, daytime sessions",
    sourceName: "LTA ClubSpark - Learn @ Southwark Park",
    sourceUrl:
      "https://clubspark.lta.org.uk/LearnAtSouthwarkPark/Coaching/Camps",
  },
  {
    title: "Summer School On-Farm Learning at Vauxhall City Farm",
    description:
      "Community holiday learning sessions on a working city farm covering topics such as animal care, gardening and ecology, run for local families throughout the summer break.",
    category: "Nature",
    borough: "Lambeth",
    venue: "Vauxhall City Farm",
    address: "165 Tyers Street, London SE11 5HS",
    lat: 51.4877,
    lng: -0.1218,
    ageMin: 5,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times: "Tuesday - Sunday, 10:30am - 4pm",
    sourceName: "Vauxhall City Farm",
    sourceUrl:
      "https://vauxhallcityfarm.org/programmes-training/summer-school/",
  },
  {
    title: "Summer Holiday Club at Brixton Recreation Centre",
    description:
      "Full-day multi-activity holiday club with arts and crafts, court games and swimming, plus optional add-ons such as the climbing wall and fitness classes.",
    category: "Multi-activity Camp",
    borough: "Lambeth",
    venue: "Brixton Recreation Centre",
    address: "27 Brixton Station Road, London SW9 8QQ",
    lat: 51.4622,
    lng: -0.1157,
    ageMin: 8,
    ageMax: 15,
    isFree: false,
    priceMin: 21.55,
    priceMax: 26.5,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times: "Weekdays, 9am - 4pm",
    sourceName: "Active Lambeth",
    sourceUrl: "https://active.lambeth.gov.uk/activities/holiday-activities/",
  },
  {
    title: "Clapham Library Code Club",
    description:
      "Free weekly drop-in coding club where children learn Scratch, build websites, and explore 3D printing and micro:bits, run at the Mary Seacole Centre.",
    category: "STEM",
    borough: "Lambeth",
    venue: "Clapham Library (Mary Seacole Centre)",
    address: "91 Clapham High Street, London SW4 7DB",
    lat: 51.4636,
    lng: -0.1367,
    ageMin: 8,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-26",
    endDate: "2026-09-06",
    times: "Sundays, 2pm - 3pm",
    sourceName: "Lambeth Council",
    sourceUrl: "https://www.lambeth.gov.uk/events/clapham-library-code-club",
  },
  {
    title:
      "Wandsworth Connected – Holiday Activities & Food Programme (Summer 2026)",
    description:
      "Free holiday clubs offering sport, arts, crafts and a daily nutritious meal for Wandsworth children on benefits-related free school meals, delivered at venues across the borough during the summer holidays.",
    category: "Multi-activity Camp",
    borough: "Wandsworth",
    venue: "Wandsworth Council (Wandsworth Connected)",
    address: "Wandsworth Town Hall, Wandsworth High Street, London SW18 2PU",
    lat: 51.4567,
    lng: -0.1926,
    ageMin: 4,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times:
      "Varies by venue; typically weekdays 9am-4pm, booking via school-issued HAF code",
    sourceName: "Wandsworth Borough Council",
    sourceUrl:
      "https://wandsworth.gov.uk/news/news-september-2025/extension-of-holiday-programme-welcomed-with-wandsworth-s-approach-showcased-to-government",
  },
  {
    title: "Summer Reading Challenge: Read to the Beat – Wandsworth Libraries",
    description:
      "Free, nationwide children's reading scheme running at all Wandsworth libraries, encouraging 4-11 year olds to read six books over the summer for stickers and a medal, with a mini challenge for under-4s.",
    category: "Arts & Crafts",
    borough: "Wandsworth",
    venue: "Battersea Library (Wandsworth Libraries)",
    address: "265 Lavender Hill, London SW11 1JB",
    lat: 51.4636,
    lng: -0.1618,
    ageMin: 3,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-04",
    endDate: "2026-09-06",
    times: "During normal library opening hours",
    sourceName: "Wandsworth Libraries / GLL (Better)",
    sourceUrl:
      "https://www.better.org.uk/library/london/wandsworth/events-and-activities/childrens-activities/summer-reading-challenge-at-wandsworth-libraries",
  },
  {
    title: "Free Holiday Swimming Lessons – Latchmere Leisure Centre",
    description:
      "Free five-day block of 30-minute group swimming lessons for Wandsworth children in school years 2-7 who cannot yet swim 25 metres, run during the summer holidays and October half term.",
    category: "Sports",
    borough: "Wandsworth",
    venue: "Latchmere Leisure Centre",
    address: "Burns Road, Battersea, London SW11 5AD",
    lat: 51.4699,
    lng: -0.1653,
    ageMin: 6,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-10-26",
    endDate: "2026-10-30",
    times: "Weekdays, sessions at 9:00-9:30am, 11:30am-12pm or 12-12:30pm",
    sourceName: "Places Leisure (Latchmere Leisure Centre)",
    sourceUrl:
      "https://www.placesleisure.org/centres/latchmere-leisure-centre/news/free-holiday-swimming-lessons/",
  },
  {
    title: "Family Craft Saturdays – Horniman Museum and Gardens",
    description:
      "Free drop-in craft session inspired by the museum's natural history and music collections, held every Saturday afternoon in the Education Centre near the main entrance.",
    category: "Museum & Heritage",
    borough: "Lewisham",
    venue: "Horniman Museum and Gardens",
    address: "100 London Road, Forest Hill, London SE23 3PQ",
    lat: 51.439,
    lng: -0.0645,
    ageMin: 3,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-25",
    endDate: "2026-10-31",
    times: "Saturdays, 2pm-4pm (last entry 3:30pm)",
    sourceName: "Horniman Museum and Gardens",
    sourceUrl: "https://www.horniman.ac.uk/event/saturday-craft-afternoons/",
  },
  {
    title: "Summer Holiday Workshops – The Albany (Montage Theatre Arts)",
    description:
      "Week-long themed drama, music and performance courses for children, each culminating in a small show for family and friends; bursaries available for eligible Lewisham/Greenwich families.",
    category: "Music & Drama",
    borough: "Lewisham",
    venue: "The Albany",
    address: "Douglas Way, Deptford, London SE8 4AG",
    lat: 51.4776,
    lng: -0.0273,
    ageMin: 5,
    ageMax: 12,
    isFree: false,
    priceMin: 10,
    priceMax: 165,
    startDate: "2026-07-20",
    endDate: "2026-08-28",
    times: "Weekdays, daytime hours vary by week",
    sourceName: "The Albany / Montage Theatre Arts",
    sourceUrl: "https://www.thealbany.org.uk/events/summer-holiday-workshops",
  },
  {
    title: "Family Nature Discovery – Sydenham Hill Wood",
    description:
      "Free drop-in holiday sessions exploring the ancient woodland's ponds and habitats through pond-dipping and minibeast hunts, run by London Wildlife Trust.",
    category: "Nature",
    borough: "Lewisham",
    venue: "Sydenham Hill Wood",
    address: "Crescent Wood Road, Sydenham Hill, London SE26 6LS",
    lat: 51.434,
    lng: -0.0679,
    ageMin: 4,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-24",
    times:
      "Selected weekdays during summer holidays; check website for exact dates",
    sourceName: "London Wildlife Trust",
    sourceUrl:
      "https://www.wildlondon.org.uk/family-learning-events/sydenham-hill-wood",
  },
  {
    title:
      "Summer Noisy Parade – Lewisham Libraries Summer Reading Challenge Launch",
    description:
      "Free launch event for the library summer reading challenge featuring an interactive retelling of The Town Musicians of Bremen, animal mask-making and a parade around the library.",
    category: "Arts & Crafts",
    borough: "Lewisham",
    venue: "Sydenham Community Library",
    address: "210 Sydenham Road, London SE26 5SE",
    lat: 51.4295,
    lng: -0.0537,
    ageMin: 4,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-25",
    endDate: "2026-07-25",
    times: "1:00pm - 3:30pm",
    sourceName: "Lewisham Libraries",
    sourceUrl: "https://libraries.lewisham.gov.uk/events",
  },
  {
    title: "Lewisham Holiday Activities & Food (HAF) Programme – Summer 2026",
    description:
      "Free holiday clubs combining sport, arts and crafts with a daily lunch for Lewisham children aged 4-16 receiving benefits-related free school meals, delivered at venues across the borough (Bellingham, Blackheath, Catford, Deptford and more).",
    category: "Multi-activity Camp",
    borough: "Lewisham",
    venue: "London Borough of Lewisham (Laurence House)",
    address: "Laurence House, 1 Catford Road, London SE6 4RU",
    lat: 51.4452,
    lng: -0.0209,
    ageMin: 4,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-20",
    times: "Weekdays, Mon-Thu, hours vary by venue",
    sourceName: "Lewisham Council",
    sourceUrl:
      "https://lewisham.gov.uk/myservices/youth-services/holiday-activities-and-food-programme",
  },
  {
    title: "Kids Swim – Glass Mill Leisure Centre",
    description:
      "Discounted £1 casual swim sessions for children at Lewisham's main leisure centre, alongside Family Fun Swims with slides and inflatables during school holidays.",
    category: "Sports",
    borough: "Lewisham",
    venue: "Glass Mill Leisure Centre",
    address: "41 Loampit Vale, London SE13 7FT",
    lat: 51.4646,
    lng: -0.0138,
    ageMin: 4,
    ageMax: 16,
    isFree: false,
    priceMin: 1,
    priceMax: 1,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times:
      "Check centre timetable for Kids Swim and Family Fun Swim session times",
    sourceName: "Better (GLL) – Glass Mill Leisure Centre",
    sourceUrl:
      "https://www.better.org.uk/leisure-centre/london/lewisham/glass-mill-leisure-centre/half-term-glass-mill-leisure-centre",
  },
  {
    title: "Summer Storytelling Fridays",
    description:
      "Free drop-in storytelling sessions for families on the Ocean Map at the National Maritime Museum, with a different sea-themed story told by a professional storyteller each Friday, including SEN-friendly sessions.",
    category: "Museum & Heritage",
    borough: "Greenwich",
    venue: "National Maritime Museum",
    address: "Romney Road, Greenwich, London SE10 9NF",
    lat: 51.4809,
    lng: -0.0055,
    ageMin: 3,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-24",
    endDate: "2026-08-28",
    times: "Fridays, session times vary (typically 11am, 12pm, 2pm and 3pm)",
    sourceName: "Royal Museums Greenwich",
    sourceUrl:
      "https://www.rmg.co.uk/whats-on/national-maritime-museum/summer-storytelling-fridays",
  },
  {
    title: "Astronomers Take Over",
    description:
      "An interactive space-themed gallery at the National Maritime Museum where visitors meet Royal Observatory astronomers, try a Mars rover landing simulator, use spectroscopes, and join a scavenger hunt, with an optional planetarium show add-on.",
    category: "STEM",
    borough: "Greenwich",
    venue: "National Maritime Museum",
    address: "Romney Road, Greenwich, London SE10 9NF",
    lat: 51.4809,
    lng: -0.0055,
    ageMin: 4,
    ageMax: 16,
    isFree: false,
    priceMin: 8,
    priceMax: 16,
    startDate: "2026-07-25",
    endDate: "2026-09-06",
    times: "Daily, 10am - 5pm",
    sourceName: "Royal Museums Greenwich",
    sourceUrl:
      "https://www.rmg.co.uk/whats-on/national-maritime-museum/astronomers-take-over",
  },
  {
    title: "Fabulous Fridays: Summer Holiday Craft Sessions",
    description:
      "Weekly family craft sessions at Charlton House & Gardens where children make up to four different crafts per session, with a quiet/sensory room available for those needing a calm space; booking essential via Eventbrite.",
    category: "Arts & Crafts",
    borough: "Greenwich",
    venue: "Charlton House & Gardens",
    address: "Charlton Road, Charlton, London SE7 8RE",
    lat: 51.4879,
    lng: 0.0303,
    ageMin: 5,
    ageMax: 12,
    isFree: false,
    priceMin: 5,
    priceMax: 5,
    startDate: "2026-07-31",
    endDate: "2026-08-28",
    times: "Fridays, 10am-12pm or 1:30pm-3:30pm",
    sourceName: "Royal Greenwich Heritage Trust (via Visit Greenwich)",
    sourceUrl:
      "https://www.visitgreenwich.org.uk/whats-on/fabulous-fridays-summer-holiday-craft-sessions-p2610591",
  },
  {
    title: "Holiday Food and Fun (HAF) Programme",
    description:
      "Royal Greenwich's council-coordinated holiday programme offering free, enriching activities and a nutritious meal each day at venues across the borough for children who receive benefits-related free school meals, aged 4-16.",
    category: "Multi-activity Camp",
    borough: "Greenwich",
    venue: "Royal Borough of Greenwich (multiple venues)",
    address:
      "The Woolwich Centre, 35 Wellington Street, Woolwich, London SE18 6HQ",
    lat: 51.4904,
    lng: 0.0637,
    ageMin: 4,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-21",
    endDate: "2026-08-28",
    times: "Varies by provider, weekdays",
    sourceName: "Royal Borough of Greenwich",
    sourceUrl: "https://www.royalgreenwich.gov.uk/holidayfoodandfun",
  },
  {
    title: "Barracudas Holiday Camp - Trinity School",
    description:
      "A multi-activity day camp held on Trinity School's grounds offering 80+ activities including swimming, archery, motorsports and dance, with flexible full/half-day booking and before/after care.",
    category: "Multi-activity Camp",
    borough: "Croydon",
    venue: "Trinity School",
    address: "Shirley Park, Croydon CR9 7AT",
    lat: 51.3765,
    lng: -0.0655,
    ageMin: 4,
    ageMax: 14,
    isFree: false,
    priceMin: 42,
    priceMax: 58,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times: "Weekdays, 8:30am-5:30pm (extended hours available)",
    sourceName: "Barracudas",
    sourceUrl: "https://www.barracudas.co.uk/camps/croydon",
  },
  {
    title: "Croydon Holiday Activities and Food (HAF) Programme",
    description:
      "Free holiday clubs across more than 60 venues in Croydon combining sport, arts, music, drama and coding with a hot, healthy meal each day, for benefits-related free school meal-eligible children aged 4-16.",
    category: "Multi-activity Camp",
    borough: "Croydon",
    venue: "Croydon Council (multiple venues)",
    address: "Bernard Weatherill House, Mint Walk, Croydon CR0 1EA",
    lat: 51.3721,
    lng: -0.0989,
    ageMin: 4,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times: "Varies by provider, weekdays",
    sourceName: "Croydon Council",
    sourceUrl: "https://www.croydon.gov.uk/holiday-activities-and-food",
  },
  {
    title: "Summer Craft Club",
    description:
      "Free drop-in craft sessions at the Museum of Croydon inspired by the museum's collections, recommended for ages 5+ but open to younger children with an adult; capacity is limited and first-come-first-served.",
    category: "Arts & Crafts",
    borough: "Croydon",
    venue: "Museum of Croydon, Croydon Clocktower",
    address: "Katharine Street, Croydon CR9 1ET",
    lat: 51.3727,
    lng: -0.0982,
    ageMin: 3,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-22",
    endDate: "2026-09-02",
    times: "Wednesdays and Fridays, drop-in",
    sourceName: "Museum of Croydon",
    sourceUrl: "https://museumofcroydon.com/whats-on-listings",
  },
  {
    title: "Selsdon Wood Nature Reserve Family Visit",
    description:
      "A 200-acre council-managed woodland and meadow nature reserve with a wood sculpture trail, ponds and butterflies, free to explore year-round and well suited to family walks and self-guided nature spotting.",
    category: "Nature",
    borough: "Croydon",
    venue: "Selsdon Wood Nature Reserve",
    address: "Old Farleigh Road, Selsdon, Croydon CR0 9HW",
    lat: 51.3436,
    lng: -0.0577,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-25",
    endDate: "2026-09-06",
    times: "Open daily, daylight hours",
    sourceName: "Croydon Council",
    sourceUrl:
      "https://www.croydon.gov.uk/node/3173/selsdon-wood-nature-reserve",
  },
  {
    title: "Half Term Junior Gym and Swimming Short Courses",
    description:
      "Recurring half-term swim short courses (Pre-School, Junior Beginners and Junior Improver levels) and all-day Junior Gym sessions at South Norwood Leisure Centre, run every school half term.",
    category: "Sports",
    borough: "Croydon",
    venue: "South Norwood Leisure Centre",
    address: "164 Portland Road, South Norwood, London SE25 4PT",
    lat: 51.3958,
    lng: -0.0794,
    ageMin: 4,
    ageMax: 11,
    isFree: false,
    priceMin: 6,
    priceMax: 10,
    startDate: "2026-10-19",
    endDate: "2026-10-23",
    times: "Weekdays, 9am-6pm (swim lessons 9am-12noon)",
    sourceName: "Better (GLL)",
    sourceUrl:
      "https://www.better.org.uk/leisure-centre/london/croydon/south-norwood-leisure-centre/half-term-south-norwood-leisure-centre",
  },
  {
    title: "Dinosaur Playground & Crystal Palace Dinosaurs",
    description:
      "A sensory-rich, accessible playground on the Dinosaur Park islands next to the restored Grade I-listed Victorian dinosaur sculptures, free to explore during normal park hours.",
    category: "Nature",
    borough: "Bromley",
    venue: "Crystal Palace Park",
    address: "Thicket Road, Penge, London SE20 8DT",
    lat: 51.4185561,
    lng: -0.0621988,
    ageMin: 2,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-24",
    endDate: "2026-09-06",
    times: "Open daily, 7:30am - 8:30pm (4:30pm in winter)",
    sourceName: "Crystal Palace Park Trust",
    sourceUrl:
      "https://www.crystalpalaceparktrust.org/pages/crystal-palace-park-dinosaur-playground-opens-march-2026",
  },
  {
    title: "Greenwich Fair – Greenwich+Docklands International Festival",
    description:
      "A free weekend of outdoor circus, dance and puppetry on the Grand Ascent in Greenwich Park, including the aerial spectacle 'ElevateHer' and street dance piece 'BUG', as part of GDIF.",
    category: "Music & Drama",
    borough: "Greenwich",
    venue: "Greenwich Park (Grand Ascent)",
    address: "Greenwich Park, London SE10 8XJ",
    lat: 51.4721658,
    lng: 0.0035489,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-22",
    endDate: "2026-08-23",
    times: "1pm - 6pm, unticketed",
    sourceName: "Time Out London",
    sourceUrl:
      "https://www.timeout.com/london/theatre/greenwich-and-docklands-international-festival",
  },
  {
    title: "Summer at Battersea Park Children's Zoo",
    description:
      "Meet meerkats, monkeys, wallabies and more at this small family zoo inside Battersea Park, with keeper talks and play areas included in admission.",
    category: "Nature",
    borough: "Wandsworth",
    venue: "Battersea Park Children's Zoo",
    address: "Battersea Park, Carriage Drive North, London SW11 4NJ",
    lat: 51.4811854,
    lng: -0.1565664,
    ageMin: 0,
    ageMax: 12,
    isFree: false,
    priceMin: 8.95,
    priceMax: 35.5,
    startDate: "2026-07-24",
    endDate: "2026-09-06",
    times: "Summer hours: daily 10am - 5:30pm (last entry 4:30pm)",
    sourceName: "Battersea Park Children's Zoo",
    sourceUrl: "https://www.batterseaparkzoo.co.uk/tickets/prices/",
  },
  {
    title: "Mini Explorers Drop-In Family Art Sessions",
    description:
      "Free drop-in art-making sessions for young children and their families, exploring the Gallery's collection through stories and hands-on making, part of the Summer Family Festival.",
    category: "Arts & Crafts",
    borough: "Southwark",
    venue: "Dulwich Picture Gallery",
    address: "Gallery Road, Dulwich Village, London SE21 7AD",
    lat: 51.4459604,
    lng: -0.0863251,
    ageMin: 2,
    ageMax: 8,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-21",
    endDate: "2026-08-25",
    times: "Drop-in, check gallery for daily session times",
    sourceName: "Dulwich Picture Gallery",
    sourceUrl:
      "https://www.dulwichpicturegallery.org.uk/whats-on/summer-family-festival-2/",
  },
  {
    title: "Jeppe Hein: Appearing Rooms",
    description:
      "A summer favourite returns to the Southbank Centre site with water fountains to splash around and cool down in — a free outdoor art installation the whole family can enjoy.",
    category: "Arts & Crafts",
    borough: "Lambeth",
    venue: "Southbank Centre",
    address: "Belvedere Road, London SE1 8XX",
    lat: 51.5057,
    lng: -0.1166,
    ageMin: 0,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-09-06",
    times: "Daily, during Southbank Centre site opening hours",
    sourceName: "Southbank Centre",
    sourceUrl: "https://www.southbankcentre.co.uk/activity/jeppe-hein-appearing-rooms/",
  },
  {
    title: "Luke Jerram: Stepping Out",
    description:
      "An interactive outdoor installation on the Riverside Terrace where footsteps make the music — walk, jump and dance across the light-up panels to trigger different sounds.",
    category: "Arts & Crafts",
    borough: "Lambeth",
    venue: "Southbank Centre (Riverside Terrace)",
    address: "Belvedere Road, London SE1 8XX",
    lat: 51.5057,
    lng: -0.1166,
    ageMin: 0,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-09-30",
    times: "Daily, during Southbank Centre site opening hours",
    sourceName: "Southbank Centre",
    sourceUrl: "https://www.southbankcentre.co.uk/whats-on/luke-jerram-stepping-out/",
  },
  {
    title: "Klaus Weber: Thinking Fountains",
    description:
      "A series of water fountains topped with bronze figures dotted around the Southbank Centre site, free to explore any time you're passing through.",
    category: "Arts & Crafts",
    borough: "Lambeth",
    venue: "Southbank Centre",
    address: "Belvedere Road, London SE1 8XX",
    lat: 51.5057,
    lng: -0.1166,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-09-06",
    times: "Daily, during Southbank Centre site opening hours",
    sourceName: "Southbank Centre",
    sourceUrl: "https://www.southbankcentre.co.uk/activity/klaus-weber-thinking-fountains/",
  },
  {
    title: "Jeppe Hein: Modified Social Benches",
    description:
      "Playful, reshaped public benches scattered around the Southbank Centre site — fun for kids to clamber over and adults to puzzle over, free to visit any time.",
    category: "Arts & Crafts",
    borough: "Lambeth",
    venue: "Southbank Centre",
    address: "Belvedere Road, London SE1 8XX",
    lat: 51.5057,
    lng: -0.1166,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-09-06",
    times: "Daily, during Southbank Centre site opening hours",
    sourceName: "Southbank Centre",
    sourceUrl: "https://www.southbankcentre.co.uk/activity/jeppe-hein-benches/",
  },
  {
    title: "Free Play in London's Only Children-Only Park",
    description:
      "A seven-acre park and playground in Bloomsbury with adventure play equipment, one of London's longest slides, sports pitches and a paddling pool; adults may only enter accompanied by a child, keeping it a genuinely child-centred green space in central London.",
    category: "Sports",
    borough: "Camden",
    venue: "Coram's Fields",
    address: "93 Guilford Street, London WC1N 1DN",
    lat: 51.5235,
    lng: -0.1201,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Open daily, roughly 9am until dusk; free under-5s drop-in play weekday mornings; free sports sessions for ages 5-19",
    sourceName: "Coram's Fields",
    sourceUrl: "https://coramsfields.org/",
  },
  {
    title: "Islington's Free Local History Museum",
    description:
      "A small, free local-history museum tracing Islington's past — from Spa Green's spa-town origins to Joe Orton and The Clash — with family-friendly displays and rotating exhibitions.",
    category: "Museum & Heritage",
    borough: "Islington",
    venue: "Islington Museum",
    address: "245 St John Street, London EC1V 4NB",
    lat: 51.5281,
    lng: -0.1057,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Mon, Tue, Thu, Fri, Sat 10am-5pm (closed 1-2pm); closed Wed & Sun",
    sourceName: "Islington Council",
    sourceUrl: "https://www.islington.gov.uk/libraries-arts-and-heritage/heritage/islington-museum",
  },
  {
    title: "Meet the Animals at Hackney City Farm",
    description:
      "A free community farm behind Broadway Market with pigs, goats, sheep and a donkey, plus an orchard and vegetable garden — a relaxed, low-cost morning out for younger children.",
    category: "Nature",
    borough: "Hackney",
    venue: "Hackney City Farm",
    address: "1a Goldsmiths Row, London E2 8QA",
    lat: 51.5313,
    lng: -0.0654,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Tuesday-Sunday 10am-4.30pm; closed Mondays except bank holidays",
    sourceName: "Hackney City Farm",
    sourceUrl: "https://hackneycityfarm.co.uk/",
  },
  {
    title: "32 Acres of City Farm Beside Canary Wharf",
    description:
      "One of Europe's largest city farms, on the Isle of Dogs, with cows, llamas, sheep and rare-breed pigs grazing against a backdrop of Canary Wharf skyscrapers; free to explore, with a café for breakfast or lunch.",
    category: "Nature",
    borough: "Tower Hamlets",
    venue: "Mudchute Park and Farm",
    address: "Pier Street, Isle of Dogs, London E14 3HP",
    lat: 51.4907,
    lng: -0.0098,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily 9am-4pm (courtyard, shop and café closed Mondays); animal feeding at 9am and 3pm",
    sourceName: "Mudchute Park and Farm",
    sourceUrl: "https://www.mudchute.org/",
  },
  {
    title: "Sand, Water and Wobbly Bridges at Tumbling Bay",
    description:
      "An award-winning natural adventure playground in Queen Elizabeth Olympic Park with sand pits, water channels kids can dam and redirect, tree houses and balancing bridges — free, and open around the clock.",
    category: "Nature",
    borough: "Newham",
    venue: "Tumbling Bay Playground, Queen Elizabeth Olympic Park",
    address: "Olympic Park Avenue, London E20 1DY",
    lat: 51.5477,
    lng: -0.0087,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Open 24 hours daily; nearby Timber Lodge café open 9.30am-5pm",
    sourceName: "Queen Elizabeth Olympic Park",
    sourceUrl: "https://www.queenelizabetholympicpark.co.uk/explore-park/parklands-and-playgrounds/tumbling-bay-playground",
  },
  {
    title: "Europe's Largest Urban Wetland Reserve",
    description:
      "A network of Victorian reservoirs turned wildlife haven, with waterside walking and cycling trails, a heron colony and a visitor centre in a converted Coal House — free entry year-round.",
    category: "Nature",
    borough: "Waltham Forest",
    venue: "Walthamstow Wetlands",
    address: "2 Forest Road, London N17 9NH",
    lat: 51.5859,
    lng: -0.0655,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "April-September daily 9.30am-5pm; October-March daily 9.30am-4pm",
    sourceName: "Walthamstow Wetlands",
    sourceUrl: "https://walthamstowwetlands.com/opening-times",
  },
  {
    title: "Tudor Manor House and Free Local History Archive",
    description:
      "A Grade I-listed Tudor manor house set in its own parkland, housing Haringey's local-history collections (including the world's first pillar box) with family activities on open days.",
    category: "Museum & Heritage",
    borough: "Haringey",
    venue: "Bruce Castle Museum",
    address: "Lordship Lane, London N17 8NU",
    lat: 51.5952,
    lng: -0.0759,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Wed-Fri 10am-12.30pm & 1.30-4pm, plus every second Saturday of the month, same hours; booking essential; grounds/park open daily",
    sourceName: "Bruce Castle Museum",
    sourceUrl: "https://brucecastle.org/visit-us/opening-hours",
  },
  {
    title: "Jacobean Mansion, Vineyard and Community Farm",
    description:
      "A free Jacobean mansion, walled garden and community farm in Enfield, with rare-breed animals, an orchard, a market garden and London's only organic commercial vineyard.",
    category: "Nature",
    borough: "Enfield",
    venue: "Forty Hall Estate & Farm",
    address: "Forty Hill, Enfield EN2 9HA",
    lat: 51.6737,
    lng: -0.0759,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Gardens open daily 8.30am-6.30pm (summer); farm animal areas open Saturday-Sunday 11am-3pm (last entry 2.30pm)",
    sourceName: "Forty Hall Estate",
    sourceUrl: "https://www.fortyhallestate.co.uk/plan-your-visit",
  },
  {
    title: "Europe's First Traditional Hindu Stone Temple",
    description:
      "A striking hand-carved marble-and-limestone landmark, free to visit daily for anyone curious about its craftsmanship and Hindu culture; the small permanent exhibition beneath the temple carries a modest separate charge.",
    category: "Museum & Heritage",
    borough: "Brent",
    venue: "BAPS Shri Swaminarayan Mandir (Neasden Temple)",
    address: "105-119 Brentfield Road, Neasden, London NW10 8LD",
    lat: 51.554,
    lng: -0.253,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily 9am-6pm; exhibition (small separate fee) has its own hours",
    sourceName: "Neasden Temple",
    sourceUrl: "https://www.neasdentemple.org/visit-us",
  },
  {
    title: "Grade II-Listed Park with Ornamental Lake",
    description:
      "A 28-acre park in the heart of Ealing, once the grounds of Pitzhanger Manor, with an ornamental bridge, a pond, a rose garden and a playground — free and open from early morning until dusk.",
    category: "Nature",
    borough: "Ealing",
    venue: "Walpole Park",
    address: "Mattock Lane, Ealing, London W5 5BG",
    lat: 51.5133,
    lng: -0.3048,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily, 7.30am until dusk",
    sourceName: "Ealing.com",
    sourceUrl: "https://www.ealing.com/walpole-park/",
  },
  {
    title: "Free Riverside Gardens at a Former Bishop's Palace",
    description:
      "The former riverside home of the Bishops of London, with acres of free-to-enter walled botanic gardens, an orchard and a moat trail beside the Thames; the museum and historic rooms keep their own hours within the free site.",
    category: "Museum & Heritage",
    borough: "Hammersmith and Fulham",
    venue: "Fulham Palace",
    address: "Bishop's Avenue, Fulham, London SW6 6EA",
    lat: 51.4735,
    lng: -0.2131,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Gardens open daily; museum & historic rooms 10.30am-5pm (last entry 4.30pm); café 9.30am-4pm",
    sourceName: "Fulham Palace",
    sourceUrl: "https://www.fulhampalace.org/visit/opening-times/",
  },
  {
    title: "Dinosaurs and a Blue Whale, Free Entry",
    description:
      "World-famous dinosaur skeletons, a blue whale suspended over Hintze Hall, and interactive earthquake and space galleries — permanent collections are free, with a free timed-entry slot bookable online.",
    category: "Museum & Heritage",
    borough: "Kensington and Chelsea",
    venue: "Natural History Museum",
    address: "Cromwell Road, London SW7 5BD",
    lat: 51.4967,
    lng: -0.1764,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily 10am-5.50pm (last entry 5.30pm); closed 24-26 December; free timed-entry booking recommended",
    sourceName: "Natural History Museum",
    sourceUrl: "https://www.nhm.ac.uk/visit.html",
  },
  {
    title: "Woodland Garden Inside Richmond Park",
    description:
      "A 40-acre woodland garden inside Richmond Park, famous for its spring azaleas but beautiful year-round, with ponds, streams and free-roaming deer nearby — always free, open dawn to dusk.",
    category: "Nature",
    borough: "Richmond upon Thames",
    venue: "Isabella Plantation, Richmond Park",
    address: "Richmond Park, Richmond TW10 5HS",
    lat: 51.437,
    lng: -0.2708,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Open daily, dawn to dusk (varies seasonally, roughly 7am-7.30am opening)",
    sourceName: "The Royal Parks",
    sourceUrl: "https://www.royalparks.org.uk/visit/parks/richmond-park/isabella-plantation",
  },
  {
    title: "Ancient Forest, Meadows and a Free City Farm",
    description:
      "Ancient woodland and open meadows on the London/Essex border, with a small free city farm (alpacas, ponies, pigs) and a boating lake in summer; a small donation is suggested but not required.",
    category: "Nature",
    borough: "Redbridge",
    venue: "Hainault Forest Country Park & Foxburrows Farm",
    address: "Romford Road, Chigwell, IG7 4QN",
    lat: 51.6187,
    lng: 0.1354,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Farm open daily 10am-5pm (4pm in winter); visitor centre 10am-4pm daily",
    sourceName: "Hainault Forest",
    sourceUrl: "https://hainaultforest.org/discover-the-forest/foxburrows-farm/",
  },
  {
    title: "Unusual Farm Animals in Feltham",
    description:
      "A 29-acre working farm with an unusual mix of animals — five breeds of pig, alpacas, rheas and peacocks among them — plus play areas and a café; modestly priced entry keeps it well under the £10 mark per child.",
    category: "Nature",
    borough: "Hounslow",
    venue: "Hounslow Urban Farm",
    address: "Faggs Road, Feltham, TW14 0LZ",
    lat: 51.455,
    lng: -0.423,
    ageMin: 0,
    ageMax: 16,
    isFree: false,
    priceMin: 6,
    priceMax: 7.5,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily 10am-5pm; closed 25 Dec, 26 Dec, 1 Jan",
    sourceName: "Hounslow Urban Farm",
    sourceUrl: "https://hounslowurbanfarm.co.uk/plan-your-visit/",
  },
  {
    title: "Free Family Art Workshops & Roden Centre Drop-In",
    description:
      "Free, no-booking-needed art-making sessions and self-led trails for families in the Roden Centre for Creative Learning, running every weekend and school holiday alongside the gallery's world-famous collection.",
    category: "Arts & Crafts",
    borough: "Westminster",
    venue: "National Gallery",
    address: "Trafalgar Square, London WC2N 5DN",
    lat: 51.5089,
    lng: -0.1283,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Roden Centre for Creative Learning open daily during summer holidays 10am-6pm; free drop-in activities every weekend and school holiday year-round",
    sourceName: "National Gallery",
    sourceUrl: "https://www.nationalgallery.org.uk/visiting/family-activities",
  },
  {
    title: "Household Cavalry Museum",
    description:
      "A working stables and museum on Horse Guards Parade where children can see the Queen's Life Guard's horses, try on cavalry kit and use interactive touchscreen guides; family events run in school holidays.",
    category: "Museum & Heritage",
    borough: "Westminster",
    venue: "Household Cavalry Museum",
    address: "Horse Guards, Whitehall, London SW1A 2AX",
    lat: 51.5049,
    lng: -0.1273,
    ageMin: 0,
    ageMax: 16,
    isFree: false,
    priceMin: 8,
    priceMax: 11,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily 10am-6pm (Apr-Oct), 10am-5pm (Nov-Mar); closed 24-26 Dec and Good Friday",
    sourceName: "Household Cavalry Museum",
    sourceUrl: "https://householdcavalrymuseum.co.uk/visit/",
  },
  {
    title: "Marylebone Library Rhymetime",
    description:
      "A free weekly drop-in session of rhymes, songs and musical instruments for under-5s and their parents/carers at Westminster's council-run Marylebone Library — no booking required.",
    category: "Music & Drama",
    borough: "Westminster",
    venue: "Marylebone Library",
    address: "9 New Cavendish Street, London W1G 9UQ",
    lat: 51.5199,
    lng: -0.1483,
    ageMin: 0,
    ageMax: 5,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Weekly Rhymetime session, term-time and holidays; check library noticeboard/website for current day and time",
    sourceName: "Westminster City Council Libraries",
    sourceUrl: "https://fisd.westminster.gov.uk/kb5/westminster/fis/service.page?id=O7GbHaV8tMI&familychannel=7",
  },
  {
    title: "Barbican Family Days & Drop-In Workshops",
    description:
      "Free family days, drop-in art and film workshops and a jungle-like Conservatory make the Barbican a low-cost arts outing for all ages, right in the heart of the City.",
    category: "Arts & Crafts",
    borough: "City of London",
    venue: "Barbican Centre",
    address: "Silk Street, London EC2Y 8DS",
    lat: 51.52,
    lng: -0.0933,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Free family days and drop-in workshops on selected weekends and school holidays; check What's On for current dates",
    sourceName: "Barbican Centre",
    sourceUrl: "https://www.barbican.org.uk/your-visit/general-info/families",
  },
  {
    title: "Lord Mayor's Show",
    description:
      "A three-mile procession of over 7,000 participants from Mansion House through the City, this free annual pageant is designed as a family's first Lord Mayor's Show, with bands, floats and an evening fireworks display.",
    category: "Music & Drama",
    borough: "City of London",
    venue: "Lord Mayor's Show (procession from Mansion House)",
    address: "Mansion House, Walbrook, London EC4N 8BH",
    lat: 51.5133,
    lng: -0.0901,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-11-14",
    endDate: "2026-11-14",
    times: "Saturday 14 November 2026, procession 11am-2pm; fireworks in the evening",
    sourceName: "City of London Corporation / Lord Mayor's Show",
    sourceUrl: "https://lordmayorsshow.london/",
  },
  {
    title: "British Museum Family Backpacks & Explorer Trails",
    description:
      "Free themed activity backpacks (refundable £10 deposit) and free downloadable explorer trails guide families around the world's collections, from Egyptian mummies to becoming an archaeologist for the day.",
    category: "Museum & Heritage",
    borough: "Camden",
    venue: "British Museum",
    address: "Great Russell Street, London WC1B 3DG",
    lat: 51.5194,
    lng: -0.127,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Museum open daily 10am-5pm (Fri until 8:30pm); Families Desk backpacks/trails available weekends and school holidays 10am-12:30pm and 1:15-4:30pm",
    sourceName: "British Museum",
    sourceUrl: "https://www.britishmuseum.org/visit/family-visits",
  },
  {
    title: "Gloucester Gate Playground, Regent's Park",
    description:
      "A free playground on the Camden side of Regent's Park with a timber treehouse built into a giant sandpit, close to London Zoo — a favourite for younger and more adventurous children alike.",
    category: "Nature",
    borough: "Camden",
    venue: "Gloucester Gate Playground, Regent's Park",
    address: "11 Gloucester Gate, Regent's Park, London NW1 4HG",
    lat: 51.535,
    lng: -0.1467,
    ageMin: 0,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily, dawn to dusk",
    sourceName: "The Royal Parks",
    sourceUrl: "https://www.royalparks.org.uk/visit/parks/regents-park-primrose-hill/gloucester-gate-playground",
  },
  {
    title: "Ironmonger Row Baths Public Swim",
    description:
      "Islington Council's historic Better-run baths offer cheap pay-as-you-go public swimming for children in a 30.5m main pool and a smaller teaching pool with a moveable floor.",
    category: "Sports",
    borough: "Islington",
    venue: "Ironmonger Row Baths",
    address: "1 Norman Street, London EC1V 3AA",
    lat: 51.5271,
    lng: -0.0956,
    ageMin: 0,
    ageMax: 16,
    isFree: false,
    priceMin: 4.15,
    priceMax: 5.8,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Public swim sessions daily; check Better UK's Ironmonger Row timetable for current session times",
    sourceName: "Better / Islington Council",
    sourceUrl: "https://www.better.org.uk/leisure-centre/london/islington/ironmonger-row-baths/prices",
  },
  {
    title: "Angel Canal Festival",
    description:
      "A free, family-friendly annual festival (its 40th year in 2026) along Regent's Canal at City Road Basin, with a children's fun fair, Punch & Judy, storytelling, boat trips and live music.",
    category: "Music & Drama",
    borough: "Islington",
    venue: "City Road Basin & Regent's Canal towpath",
    address: "City Road Basin, Wharf Road, London N1 7RG",
    lat: 51.5308,
    lng: -0.0947,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-09-06",
    endDate: "2026-09-06",
    times: "Sunday 6 September 2026, approx. 11am-5pm (fun-fair rides individually charged)",
    sourceName: "Angel Canal Festival",
    sourceUrl: "https://www.angelcanalfestival.co.uk/",
  },
  {
    title: "Science Museum Free Galleries",
    description:
      "Free, pre-booked timed entry to hands-on galleries including Space, Making the Modern World and Mathematics: The Winton Gallery; the interactive Wonderlab and Power Up galleries are a separate paid add-on.",
    category: "STEM",
    borough: "Kensington and Chelsea",
    venue: "Science Museum",
    address: "Exhibition Road, South Kensington, London SW7 2DD",
    lat: 51.4978,
    lng: -0.1745,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily 10am-6pm; free timed-entry tickets must be pre-booked online",
    sourceName: "Science Museum",
    sourceUrl: "https://www.sciencemuseum.org.uk/visit",
  },
  {
    title: "V&A Summer Family Festival",
    description:
      "Free drop-in workshops, playful installations and performances — music, dance, storytelling, crafts and circus — themed around making and materials, in the V&A's free-to-enter South Kensington galleries.",
    category: "Arts & Crafts",
    borough: "Kensington and Chelsea",
    venue: "V&A South Kensington",
    address: "Cromwell Road, London SW7 2RL",
    lat: 51.4966,
    lng: -0.1722,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-11",
    endDate: "2026-08-28",
    times: "Free workshops 11-13 August, drop-in family activities 17-28 August 2026, approx. 11am-4pm",
    sourceName: "V&A",
    sourceUrl: "https://www.vam.ac.uk/festival/2026/summer-holidays-2026",
  },
  {
    title: "Serpentine Family Days",
    description:
      "Free, drop-in hands-on workshops on the Serpentine's lawn — natural dyeing, weaving, seed-sowing and outdoor games — inspired by the current Pavilion and exhibitions; bring a picnic.",
    category: "Arts & Crafts",
    borough: "Kensington and Chelsea",
    venue: "Serpentine South Gallery",
    address: "Kensington Gardens, London W2 3XA",
    lat: 51.5045,
    lng: -0.1732,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Free drop-in family days on selected dates — check Serpentine website for the current 2026 schedule",
    sourceName: "Serpentine Galleries",
    sourceUrl: "https://www.serpentinegalleries.org/whats-on/serpentine-family-days-2026/",
  },
  {
    title: "Round Pond & Elfin Oak, Kensington Gardens",
    description:
      "Feed the ducks and swans at the Round Pond and spot the 74 carved elves, gnomes and fairies on the 900-year-old Elfin Oak — a free, always-open nature trail for younger children.",
    category: "Nature",
    borough: "Kensington and Chelsea",
    venue: "Kensington Gardens (Round Pond & Elfin Oak)",
    address: "Broad Walk, Kensington Gardens, London W2 4RU",
    lat: 51.5073,
    lng: -0.1875,
    ageMin: 0,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Daily 6am-dusk",
    sourceName: "The Royal Parks",
    sourceUrl: "https://www.royalparks.org.uk/visit/parks/kensington-gardens",
  },
  {
    title: "Saatchi Gallery Family Art Workshops",
    description:
      "Free-entry contemporary art gallery in Chelsea running Sunday Family Art Workshops (suggested £5 donation) and free Family Days in school holidays, both built around the current exhibition.",
    category: "Arts & Crafts",
    borough: "Kensington and Chelsea",
    venue: "Saatchi Gallery",
    address: "Duke of York's HQ, King's Road, Chelsea, London SW3 4RY",
    lat: 51.4899,
    lng: -0.159,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 5,
    startDate: "2026-07-28",
    endDate: "2026-12-31",
    times: "Gallery open daily 10am-6pm; Sunday Family Art Workshops (suggested £5 donation); free Family Days in school holidays",
    sourceName: "Saatchi Gallery",
    sourceUrl: "https://www.saatchigallery.com/whats-on",
  },
  {
    title: "RAF Museum London Free Galleries, Aeroplay & STEM Zones",
    description:
      "Free entry to explore over 100 historic aircraft including Spitfires and Lancaster bombers, plus an aviation-themed outdoor playground, the AeroPlay soft-play area, and hands-on STEM Zones exploring flight and engineering.",
    category: "Museum & Heritage, STEM",
    borough: "Barnet",
    venue: "RAF Museum London",
    address: "Grahame Park Way",
    lat: 51.5980125,
    lng: -0.2389297,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-04",
    endDate: "2026-12-31",
    times: "Daily, check website for hours",
    sourceName: "RAF Museum London",
    sourceUrl: "https://www.rafmuseum.org.uk/london/things-to-see-and-do/",
  },
  {
    title: "Summer Junior Gym at Barnet Copthall Leisure Centre",
    description:
      "A dedicated summer holiday junior gym session for 11-17 year olds (induction required, free weights not permitted for juniors), running on weekdays throughout the school summer break.",
    category: "Sports",
    borough: "Barnet",
    venue: "Barnet Copthall Leisure Centre",
    address: "Champions Way, Hendon",
    lat: 51.604578,
    lng: -0.2280232,
    ageMin: 11,
    ageMax: 17,
    isFree: false,
    priceMin: 5.2,
    priceMax: 5.2,
    startDate: "2026-08-04",
    endDate: "2026-08-31",
    times: "Mon-Fri 10:30am-3:30pm",
    sourceName: "Better (GLL) / Barnet Copthall Leisure Centre",
    sourceUrl:
      "https://www.better.org.uk/leisure-centre/london/barnet/barnet-copthall-leisure-centre/holiday-activities-barnet-copthall-leisure-centre",
  },
  {
    title: "Barnet Libraries Summer Reading Challenge 2026: Read to the Beat",
    description:
      "Children aged 4-12 sign up at any Barnet library and read six books over the summer holidays to collect rewards and earn a certificate and medal, with bonus events including a DJ workshop and STEM Jams during August.",
    category: "Arts & Crafts",
    borough: "Barnet",
    venue: "Chipping Barnet Library",
    address: "3 Stapylton Road, Barnet",
    lat: 51.6541351,
    lng: -0.2054167,
    ageMin: 4,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-04",
    endDate: "2026-08-31",
    times: "During staffed library hours",
    sourceName: "Barnet Council",
    sourceUrl:
      "https://www.barnet.gov.uk/libraries/children-and-young-peoples-library-services/summer-reading-challenge-2026",
  },
  {
    title: "Holiday HQ Summer Camp at Harrow Leisure Centre",
    description:
      "A full-day holiday camp for primary-age children combining daily swimming, soft play, sports-hall games and an astro pitch, with themed extras like a UV silent disco and Zoolab animal encounters.",
    category: "Multi-activity Camp, Sports",
    borough: "Harrow",
    venue: "Harrow Leisure Centre",
    address: "Christchurch Avenue",
    lat: 51.5926121,
    lng: -0.3275961,
    ageMin: 5,
    ageMax: 11,
    isFree: false,
    priceMin: 43.55,
    priceMax: 43.55,
    startDate: "2026-08-04",
    endDate: "2026-08-28",
    times: "08:30-17:30",
    sourceName: "Junior Adventures Group",
    sourceUrl: "https://www.junioradventuresgroup.co.uk/find-us/harrow-leisure-centre/",
  },
  {
    title: "Eliza's Pet Trail at Headstone Manor & Museum",
    description:
      "A free drop-in trail around the moated medieval manor grounds, hunting for the hidden names of Victorian naturalist Eliza Brightwen's unusual pets to win a prize.",
    category: "Museum & Heritage, Nature",
    borough: "Harrow",
    venue: "Headstone Manor & Museum",
    address: "Headstone Recreation Ground, Pinner View",
    lat: 51.5947055,
    lng: -0.3542185,
    ageMin: 3,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-05",
    endDate: "2026-08-30",
    times: "During normal museum opening hours",
    sourceName: "Headstone Manor & Museum",
    sourceUrl: "https://headstonemanor.org/events/elizas-pet-trail/",
  },
  {
    title: "SUMMIT Rooftop Walk at Alexandra Palace",
    description:
      "A harnessed guided walk across the UK's highest roof, with panoramic views over London from Alexandra Palace's Victorian roofline (minimum age 8, minimum height 1.2m).",
    category: "Sports",
    borough: "Haringey",
    venue: "Alexandra Palace",
    address: "Alexandra Palace Way",
    lat: 51.5943495,
    lng: -0.1306402,
    ageMin: 8,
    ageMax: 16,
    isFree: false,
    priceMin: 19.25,
    priceMax: 19.25,
    startDate: "2026-08-04",
    endDate: "2026-12-31",
    times: "Check website for available slot times",
    sourceName: "Alexandra Palace",
    sourceUrl: "https://www.alexandrapalace.com/things-to-do/summer/",
  },
  {
    title: "Summer Reading Challenge Craft: Fish Pond at St Ann's Library",
    description:
      "Free drop-in craft session as part of Haringey's 'Read to the Beat' summer reading challenge, making a fish pond picture inspired by this year's music theme.",
    category: "Arts & Crafts",
    borough: "Haringey",
    venue: "St Ann's Library",
    address: "Cissbury Road, Tottenham",
    lat: 51.5814517,
    lng: -0.082934,
    ageMin: 4,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-09",
    endDate: "2026-08-13",
    times: "10:30am-12:00pm",
    sourceName: "Haringey Council",
    sourceUrl:
      "https://haringey.gov.uk/news/20260709/challenge-your-haringey-child-to-read-to-beat-with-fun-free-summer-challenge",
  },
  {
    title: "Enchanted Garden Day at Capel Manor Gardens",
    description:
      "The Manor House lawn and Fairy Forest transform into a whimsical family day with hourly storytelling, guided craft workshops, face painting and walk-around fairy characters; fancy dress encouraged.",
    category: "Arts & Crafts, Nature",
    borough: "Enfield",
    venue: "Capel Manor Gardens",
    address: "Bullsmoor Lane",
    lat: 51.6796371,
    lng: -0.0528476,
    ageMin: 3,
    ageMax: 15,
    isFree: false,
    priceMin: 10,
    priceMax: 10,
    startDate: "2026-08-08",
    endDate: "2026-08-08",
    times: "10:00am-3:00pm",
    sourceName: "Capel Manor Gardens",
    sourceUrl: "https://www.capelmanorgardens.co.uk/event/enchanted-garden-day-at-capel-manor-gardens/",
  },
  {
    title: "Forty Hall Farm Farmers' Market",
    description:
      "Free-entry monthly farmers' market at this certified organic city farm, selling seasonal vegetables, rare-breed meats and vineyard wine, with sheep, pigs and rare-breed cattle for children to meet.",
    category: "Nature",
    borough: "Enfield",
    venue: "Forty Hall Farm",
    address: "Forty Hall, Forty Hill",
    lat: 51.6696412,
    lng: -0.0682465,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-09",
    endDate: "2026-08-09",
    times: "11:00am-4:00pm",
    sourceName: "Forty Hall Farm",
    sourceUrl: "http://www.fortyhallfarm.org.uk/events.html",
  },
  {
    title: "Family Day in the Park: Morris's Magical Menagerie",
    description:
      "Free drop-in family craft day held in Lloyd Park while the William Morris Gallery is closed for refurbishment, making bold, colourful animal masks inspired by the park's wildlife.",
    category: "Arts & Crafts",
    borough: "Waltham Forest",
    venue: "Lloyd Park Bandstand",
    address: "Lloyd Park, Forest Road",
    lat: 51.5904931,
    lng: -0.0222601,
    ageMin: 4,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-08",
    endDate: "2026-08-08",
    times: "1:00pm-4:00pm",
    sourceName: "William Morris Gallery",
    sourceUrl: "https://wmgallery.org.uk/event-category/families/",
  },
  {
    title: "Urban Nature Club: Make a Stop Motion Nature Story",
    description:
      "A creative wildlife workshop at Walthamstow Wetlands' outdoor classroom where 6-12 year olds learn stop-motion animation techniques using natural materials they find on site.",
    category: "Nature, STEM, Arts & Crafts",
    borough: "Waltham Forest",
    venue: "Walthamstow Wetlands",
    address: "2 Forest Road",
    lat: 51.5855068,
    lng: -0.0541376,
    ageMin: 6,
    ageMax: 12,
    isFree: false,
    priceMin: 10,
    priceMax: 10,
    startDate: "2026-08-17",
    endDate: "2026-08-17",
    times: "1:00pm-3:00pm",
    sourceName: "London Wildlife Trust (Eventbrite)",
    sourceUrl:
      "https://www.eventbrite.co.uk/e/urban-nature-club-at-walthamstow-wetlands-make-a-stop-motion-nature-story-tickets-1993459321493",
  },
  {
    title: "Hampstead Beach at JW3",
    description:
      "A free indoor sandy beach with deck chairs, a paddling pool and a weatherproof retractable roof at Camden's Jewish community centre, with a dedicated Beach Club for under-5s on Mondays and Wednesdays.",
    category: "Sports",
    borough: "Camden",
    venue: "JW3",
    address: "341-351 Finchley Road",
    lat: 51.5509292,
    lng: -0.1847394,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-04",
    endDate: "2026-08-30",
    times: "Sun-Thu 10am-8pm, Fri 10am-5pm",
    sourceName: "JW3",
    sourceUrl: "https://www.jw3.org.uk/whats-on/family-beach-party-hp3z",
  },
  {
    title: "Little Angel Theatre Children's Puppet Festival 2026",
    description:
      "A summer-long puppetry festival marking the theatre's 65th anniversary, featuring the world premiere marionette production 'The Sorcerer's Apprentice', visiting companies performing Hansel & Gretel and Pinocchio, plus family workshops and a marionette exhibition.",
    category: "Music & Drama",
    borough: "Islington",
    venue: "Little Angel Theatre",
    address: "14 Dagmar Passage",
    lat: 51.5390442,
    lng: -0.1011857,
    ageMin: 2,
    ageMax: 16,
    isFree: false,
    priceMin: 7,
    priceMax: 14,
    startDate: "2026-08-04",
    endDate: "2026-08-30",
    times: "Varies by show",
    sourceName: "Little Angel Theatre",
    sourceUrl: "https://www.littleangeltheatre.com/little-angel-theatre-childrens-puppet-festival-2026/",
  },
];

async function main() {
  await prisma.activity.deleteMany();
  for (const activity of activities) {
    await prisma.activity.create({
      data: {
        ...activity,
        startDate: new Date(activity.startDate),
        endDate: new Date(activity.endDate),
      },
    });
  }
  console.log(`Seeded ${activities.length} activities.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
