import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL ?? "file:./dev.db",
});
const prisma = new PrismaClient({ adapter });

type Seed = {
  title: string;
  description: string;
  category: string;
  borough: string;
  venue: string;
  address: string;
  lat: number;
  lng: number;
  ageMin: number;
  ageMax: number;
  isFree: boolean;
  priceMin: number;
  priceMax: number;
  startDate: string;
  endDate: string;
  times?: string;
  sourceName: string;
  sourceUrl: string;
};

const activities: Seed[] = [
  {
    title: "Summer Holiday Family Activities at IWM London",
    description:
      "Free daily drop-in activities in the Clore Learning Centre and galleries, including building paper houses for the 'What Makes a Home?' trail and the Childhood in War stamp trail exploring young people's wartime experiences.",
    category: "Museum & Heritage",
    borough: "Lambeth",
    venue: "Imperial War Museum London",
    address: "Lambeth Road, London SE1 6HZ",
    lat: 51.4959,
    lng: -0.1092,
    ageMin: 4,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-22",
    endDate: "2026-08-23",
    times: "Daily, 10am - 4pm",
    sourceName: "Imperial War Museums",
    sourceUrl: "https://www.iwm.org.uk/events/family-activities-iwm-london",
  },
  {
    title: "October Half Term Holiday Club - Herne Hill Velodrome",
    description:
      "Track cycling and mountain biking holiday club for young riders of all abilities, with bikes and helmets available to hire and a one-hour lunch break included.",
    category: "Sports",
    borough: "Southwark",
    venue: "Herne Hill Velodrome",
    address: "104 Burbage Road, London SE24 9HE",
    lat: 51.4568,
    lng: -0.1024,
    ageMin: 8,
    ageMax: 16,
    isFree: false,
    priceMin: 10,
    priceMax: 15,
    startDate: "2026-10-19",
    endDate: "2026-10-23",
    times: "Weekdays, 10am - 3pm",
    sourceName: "Herne Hill Velodrome",
    sourceUrl: "https://www.hernehillvelodrome.com/holiday-clubs",
  },
  {
    title: "Family Visit & Pirate Training Experience at the Golden Hinde",
    description:
      "Climb aboard a full-size replica of Sir Francis Drake's Tudor galleon for a self-guided or costumed-guide tour, with a pirate-themed training session available for children aged 7 and up.",
    category: "Museum & Heritage",
    borough: "Southwark",
    venue: "The Golden Hinde",
    address: "St Mary Overie Dock, Cathedral Street, London SE1 9DE",
    lat: 51.5062,
    lng: -0.0912,
    ageMin: 5,
    ageMax: 12,
    isFree: false,
    priceMin: 6,
    priceMax: 20,
    startDate: "2026-07-27",
    endDate: "2026-09-06",
    times: "Daily, 10am - 6pm",
    sourceName: "The Golden Hinde",
    sourceUrl: "https://www.goldenhinde.co.uk/",
  },
  {
    title: "Farm Club Summer Sessions at Surrey Docks Farm",
    description:
      "Full-day sessions for children where they take part in animal care such as mucking out pens and small-animal handling, plus nature crafts, bushcraft and pond dipping on a working city farm.",
    category: "Nature",
    borough: "Southwark",
    venue: "Surrey Docks Farm",
    address: "South Wharf, Rotherhithe Street, London SE16 5ET",
    lat: 51.4967,
    lng: -0.0448,
    ageMin: 8,
    ageMax: 13,
    isFree: false,
    priceMin: 42,
    priceMax: 42,
    startDate: "2026-08-05",
    endDate: "2026-08-19",
    times: "Select dates, 10am - 4pm",
    sourceName: "Surrey Docks Farm",
    sourceUrl: "https://surreydocksfarm.org.uk/farm-club/",
  },
  {
    title: "Summer Holiday Mini Tennis Camps at Southwark Park",
    description:
      "Professionally coached tennis camps combining skill drills, games and friendly competition for young players, run on the outdoor courts in Southwark Park.",
    category: "Sports",
    borough: "Southwark",
    venue: "Southwark Park Tennis Courts",
    address: "Southwark Park, Jamaica Road, London SE16 2TX",
    lat: 51.4955,
    lng: -0.0526,
    ageMin: 5,
    ageMax: 9,
    isFree: false,
    priceMin: 20,
    priceMax: 20,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times: "Weekdays, daytime sessions",
    sourceName: "LTA ClubSpark - Learn @ Southwark Park",
    sourceUrl:
      "https://clubspark.lta.org.uk/LearnAtSouthwarkPark/Coaching/Camps",
  },
  {
    title: "Summer School On-Farm Learning at Vauxhall City Farm",
    description:
      "Community holiday learning sessions on a working city farm covering topics such as animal care, gardening and ecology, run for local families throughout the summer break.",
    category: "Nature",
    borough: "Lambeth",
    venue: "Vauxhall City Farm",
    address: "165 Tyers Street, London SE11 5HS",
    lat: 51.4877,
    lng: -0.1218,
    ageMin: 5,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times: "Tuesday - Sunday, 10:30am - 4pm",
    sourceName: "Vauxhall City Farm",
    sourceUrl:
      "https://vauxhallcityfarm.org/programmes-training/summer-school/",
  },
  {
    title: "Summer Holiday Club at Brixton Recreation Centre",
    description:
      "Full-day multi-activity holiday club with arts and crafts, court games and swimming, plus optional add-ons such as the climbing wall and fitness classes.",
    category: "Multi-activity Camp",
    borough: "Lambeth",
    venue: "Brixton Recreation Centre",
    address: "27 Brixton Station Road, London SW9 8QQ",
    lat: 51.4622,
    lng: -0.1157,
    ageMin: 8,
    ageMax: 15,
    isFree: false,
    priceMin: 21.55,
    priceMax: 26.5,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times: "Weekdays, 9am - 4pm",
    sourceName: "Active Lambeth",
    sourceUrl: "https://active.lambeth.gov.uk/activities/holiday-activities/",
  },
  {
    title: "Clapham Library Code Club",
    description:
      "Free weekly drop-in coding club where children learn Scratch, build websites, and explore 3D printing and micro:bits, run at the Mary Seacole Centre.",
    category: "STEM",
    borough: "Lambeth",
    venue: "Clapham Library (Mary Seacole Centre)",
    address: "91 Clapham High Street, London SW4 7DB",
    lat: 51.4636,
    lng: -0.1367,
    ageMin: 8,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-26",
    endDate: "2026-09-06",
    times: "Sundays, 2pm - 3pm",
    sourceName: "Lambeth Council",
    sourceUrl: "https://www.lambeth.gov.uk/events/clapham-library-code-club",
  },
  {
    title:
      "Wandsworth Connected – Holiday Activities & Food Programme (Summer 2026)",
    description:
      "Free holiday clubs offering sport, arts, crafts and a daily nutritious meal for Wandsworth children on benefits-related free school meals, delivered at venues across the borough during the summer holidays.",
    category: "Multi-activity Camp",
    borough: "Wandsworth",
    venue: "Wandsworth Council (Wandsworth Connected)",
    address: "Wandsworth Town Hall, Wandsworth High Street, London SW18 2PU",
    lat: 51.4567,
    lng: -0.1926,
    ageMin: 4,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times:
      "Varies by venue; typically weekdays 9am-4pm, booking via school-issued HAF code",
    sourceName: "Wandsworth Borough Council",
    sourceUrl:
      "https://wandsworth.gov.uk/news/news-september-2025/extension-of-holiday-programme-welcomed-with-wandsworth-s-approach-showcased-to-government",
  },
  {
    title: "Summer Reading Challenge: Read to the Beat – Wandsworth Libraries",
    description:
      "Free, nationwide children's reading scheme running at all Wandsworth libraries, encouraging 4-11 year olds to read six books over the summer for stickers and a medal, with a mini challenge for under-4s.",
    category: "Arts & Crafts",
    borough: "Wandsworth",
    venue: "Battersea Library (Wandsworth Libraries)",
    address: "265 Lavender Hill, London SW11 1JB",
    lat: 51.4636,
    lng: -0.1618,
    ageMin: 3,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-04",
    endDate: "2026-09-06",
    times: "During normal library opening hours",
    sourceName: "Wandsworth Libraries / GLL (Better)",
    sourceUrl:
      "https://www.better.org.uk/library/london/wandsworth/events-and-activities/childrens-activities/summer-reading-challenge-at-wandsworth-libraries",
  },
  {
    title: "Free Holiday Swimming Lessons – Latchmere Leisure Centre",
    description:
      "Free five-day block of 30-minute group swimming lessons for Wandsworth children in school years 2-7 who cannot yet swim 25 metres, run during the summer holidays and October half term.",
    category: "Sports",
    borough: "Wandsworth",
    venue: "Latchmere Leisure Centre",
    address: "Burns Road, Battersea, London SW11 5AD",
    lat: 51.4699,
    lng: -0.1653,
    ageMin: 6,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-10-26",
    endDate: "2026-10-30",
    times: "Weekdays, sessions at 9:00-9:30am, 11:30am-12pm or 12-12:30pm",
    sourceName: "Places Leisure (Latchmere Leisure Centre)",
    sourceUrl:
      "https://www.placesleisure.org/centres/latchmere-leisure-centre/news/free-holiday-swimming-lessons/",
  },
  {
    title: "Family Craft Saturdays – Horniman Museum and Gardens",
    description:
      "Free drop-in craft session inspired by the museum's natural history and music collections, held every Saturday afternoon in the Education Centre near the main entrance.",
    category: "Museum & Heritage",
    borough: "Lewisham",
    venue: "Horniman Museum and Gardens",
    address: "100 London Road, Forest Hill, London SE23 3PQ",
    lat: 51.439,
    lng: -0.0645,
    ageMin: 3,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-25",
    endDate: "2026-10-31",
    times: "Saturdays, 2pm-4pm (last entry 3:30pm)",
    sourceName: "Horniman Museum and Gardens",
    sourceUrl: "https://www.horniman.ac.uk/event/saturday-craft-afternoons/",
  },
  {
    title: "Summer Holiday Workshops – The Albany (Montage Theatre Arts)",
    description:
      "Week-long themed drama, music and performance courses for children, each culminating in a small show for family and friends; bursaries available for eligible Lewisham/Greenwich families.",
    category: "Music & Drama",
    borough: "Lewisham",
    venue: "The Albany",
    address: "Douglas Way, Deptford, London SE8 4AG",
    lat: 51.4776,
    lng: -0.0273,
    ageMin: 5,
    ageMax: 12,
    isFree: false,
    priceMin: 10,
    priceMax: 165,
    startDate: "2026-07-20",
    endDate: "2026-08-28",
    times: "Weekdays, daytime hours vary by week",
    sourceName: "The Albany / Montage Theatre Arts",
    sourceUrl: "https://www.thealbany.org.uk/events/summer-holiday-workshops",
  },
  {
    title: "Family Nature Discovery – Sydenham Hill Wood",
    description:
      "Free drop-in holiday sessions exploring the ancient woodland's ponds and habitats through pond-dipping and minibeast hunts, run by London Wildlife Trust.",
    category: "Nature",
    borough: "Lewisham",
    venue: "Sydenham Hill Wood",
    address: "Crescent Wood Road, Sydenham Hill, London SE26 6LS",
    lat: 51.434,
    lng: -0.0679,
    ageMin: 4,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-24",
    times:
      "Selected weekdays during summer holidays; check website for exact dates",
    sourceName: "London Wildlife Trust",
    sourceUrl:
      "https://www.wildlondon.org.uk/family-learning-events/sydenham-hill-wood",
  },
  {
    title:
      "Summer Noisy Parade – Lewisham Libraries Summer Reading Challenge Launch",
    description:
      "Free launch event for the library summer reading challenge featuring an interactive retelling of The Town Musicians of Bremen, animal mask-making and a parade around the library.",
    category: "Arts & Crafts",
    borough: "Lewisham",
    venue: "Sydenham Community Library",
    address: "210 Sydenham Road, London SE26 5SE",
    lat: 51.4295,
    lng: -0.0537,
    ageMin: 4,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-25",
    endDate: "2026-07-25",
    times: "1:00pm - 3:30pm",
    sourceName: "Lewisham Libraries",
    sourceUrl: "https://libraries.lewisham.gov.uk/events",
  },
  {
    title: "Lewisham Holiday Activities & Food (HAF) Programme – Summer 2026",
    description:
      "Free holiday clubs combining sport, arts and crafts with a daily lunch for Lewisham children aged 4-16 receiving benefits-related free school meals, delivered at venues across the borough (Bellingham, Blackheath, Catford, Deptford and more).",
    category: "Multi-activity Camp",
    borough: "Lewisham",
    venue: "London Borough of Lewisham (Laurence House)",
    address: "Laurence House, 1 Catford Road, London SE6 4RU",
    lat: 51.4452,
    lng: -0.0209,
    ageMin: 4,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-20",
    times: "Weekdays, Mon-Thu, hours vary by venue",
    sourceName: "Lewisham Council",
    sourceUrl:
      "https://lewisham.gov.uk/myservices/youth-services/holiday-activities-and-food-programme",
  },
  {
    title: "Kids Swim – Glass Mill Leisure Centre",
    description:
      "Discounted £1 casual swim sessions for children at Lewisham's main leisure centre, alongside Family Fun Swims with slides and inflatables during school holidays.",
    category: "Sports",
    borough: "Lewisham",
    venue: "Glass Mill Leisure Centre",
    address: "41 Loampit Vale, London SE13 7FT",
    lat: 51.4646,
    lng: -0.0138,
    ageMin: 4,
    ageMax: 16,
    isFree: false,
    priceMin: 1,
    priceMax: 1,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times:
      "Check centre timetable for Kids Swim and Family Fun Swim session times",
    sourceName: "Better (GLL) – Glass Mill Leisure Centre",
    sourceUrl:
      "https://www.better.org.uk/leisure-centre/london/lewisham/glass-mill-leisure-centre/half-term-glass-mill-leisure-centre",
  },
  {
    title: "Summer Storytelling Fridays",
    description:
      "Free drop-in storytelling sessions for families on the Ocean Map at the National Maritime Museum, with a different sea-themed story told by a professional storyteller each Friday, including SEN-friendly sessions.",
    category: "Museum & Heritage",
    borough: "Greenwich",
    venue: "National Maritime Museum",
    address: "Romney Road, Greenwich, London SE10 9NF",
    lat: 51.4809,
    lng: -0.0055,
    ageMin: 3,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-24",
    endDate: "2026-08-28",
    times: "Fridays, session times vary (typically 11am, 12pm, 2pm and 3pm)",
    sourceName: "Royal Museums Greenwich",
    sourceUrl:
      "https://www.rmg.co.uk/whats-on/national-maritime-museum/summer-storytelling-fridays",
  },
  {
    title: "Astronomers Take Over",
    description:
      "An interactive space-themed gallery at the National Maritime Museum where visitors meet Royal Observatory astronomers, try a Mars rover landing simulator, use spectroscopes, and join a scavenger hunt, with an optional planetarium show add-on.",
    category: "STEM",
    borough: "Greenwich",
    venue: "National Maritime Museum",
    address: "Romney Road, Greenwich, London SE10 9NF",
    lat: 51.4809,
    lng: -0.0055,
    ageMin: 4,
    ageMax: 16,
    isFree: false,
    priceMin: 8,
    priceMax: 16,
    startDate: "2026-07-25",
    endDate: "2026-09-06",
    times: "Daily, 10am - 5pm",
    sourceName: "Royal Museums Greenwich",
    sourceUrl:
      "https://www.rmg.co.uk/whats-on/national-maritime-museum/astronomers-take-over",
  },
  {
    title: "Fabulous Fridays: Summer Holiday Craft Sessions",
    description:
      "Weekly family craft sessions at Charlton House & Gardens where children make up to four different crafts per session, with a quiet/sensory room available for those needing a calm space; booking essential via Eventbrite.",
    category: "Arts & Crafts",
    borough: "Greenwich",
    venue: "Charlton House & Gardens",
    address: "Charlton Road, Charlton, London SE7 8RE",
    lat: 51.4879,
    lng: 0.0303,
    ageMin: 5,
    ageMax: 12,
    isFree: false,
    priceMin: 5,
    priceMax: 5,
    startDate: "2026-07-31",
    endDate: "2026-08-28",
    times: "Fridays, 10am-12pm or 1:30pm-3:30pm",
    sourceName: "Royal Greenwich Heritage Trust (via Visit Greenwich)",
    sourceUrl:
      "https://www.visitgreenwich.org.uk/whats-on/fabulous-fridays-summer-holiday-craft-sessions-p2610591",
  },
  {
    title: "Holiday Food and Fun (HAF) Programme",
    description:
      "Royal Greenwich's council-coordinated holiday programme offering free, enriching activities and a nutritious meal each day at venues across the borough for children who receive benefits-related free school meals, aged 4-16.",
    category: "Multi-activity Camp",
    borough: "Greenwich",
    venue: "Royal Borough of Greenwich (multiple venues)",
    address:
      "The Woolwich Centre, 35 Wellington Street, Woolwich, London SE18 6HQ",
    lat: 51.4904,
    lng: 0.0637,
    ageMin: 4,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-21",
    endDate: "2026-08-28",
    times: "Varies by provider, weekdays",
    sourceName: "Royal Borough of Greenwich",
    sourceUrl: "https://www.royalgreenwich.gov.uk/holidayfoodandfun",
  },
  {
    title: "Barracudas Holiday Camp - Trinity School",
    description:
      "A multi-activity day camp held on Trinity School's grounds offering 80+ activities including swimming, archery, motorsports and dance, with flexible full/half-day booking and before/after care.",
    category: "Multi-activity Camp",
    borough: "Croydon",
    venue: "Trinity School",
    address: "Shirley Park, Croydon CR9 7AT",
    lat: 51.3765,
    lng: -0.0655,
    ageMin: 4,
    ageMax: 14,
    isFree: false,
    priceMin: 42,
    priceMax: 58,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times: "Weekdays, 8:30am-5:30pm (extended hours available)",
    sourceName: "Barracudas",
    sourceUrl: "https://www.barracudas.co.uk/camps/croydon",
  },
  {
    title: "Croydon Holiday Activities and Food (HAF) Programme",
    description:
      "Free holiday clubs across more than 60 venues in Croydon combining sport, arts, music, drama and coding with a hot, healthy meal each day, for benefits-related free school meal-eligible children aged 4-16.",
    category: "Multi-activity Camp",
    borough: "Croydon",
    venue: "Croydon Council (multiple venues)",
    address: "Bernard Weatherill House, Mint Walk, Croydon CR0 1EA",
    lat: 51.3721,
    lng: -0.0989,
    ageMin: 4,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-09-04",
    times: "Varies by provider, weekdays",
    sourceName: "Croydon Council",
    sourceUrl: "https://www.croydon.gov.uk/holiday-activities-and-food",
  },
  {
    title: "Summer Craft Club",
    description:
      "Free drop-in craft sessions at the Museum of Croydon inspired by the museum's collections, recommended for ages 5+ but open to younger children with an adult; capacity is limited and first-come-first-served.",
    category: "Arts & Crafts",
    borough: "Croydon",
    venue: "Museum of Croydon, Croydon Clocktower",
    address: "Katharine Street, Croydon CR9 1ET",
    lat: 51.3727,
    lng: -0.0982,
    ageMin: 3,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-22",
    endDate: "2026-09-02",
    times: "Wednesdays and Fridays, drop-in",
    sourceName: "Museum of Croydon",
    sourceUrl: "https://museumofcroydon.com/whats-on-listings",
  },
  {
    title: "Selsdon Wood Nature Reserve Family Visit",
    description:
      "A 200-acre council-managed woodland and meadow nature reserve with a wood sculpture trail, ponds and butterflies, free to explore year-round and well suited to family walks and self-guided nature spotting.",
    category: "Nature",
    borough: "Croydon",
    venue: "Selsdon Wood Nature Reserve",
    address: "Old Farleigh Road, Selsdon, Croydon CR0 9HW",
    lat: 51.3436,
    lng: -0.0577,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-25",
    endDate: "2026-09-06",
    times: "Open daily, daylight hours",
    sourceName: "Croydon Council",
    sourceUrl:
      "https://www.croydon.gov.uk/node/3173/selsdon-wood-nature-reserve",
  },
  {
    title: "Half Term Junior Gym and Swimming Short Courses",
    description:
      "Recurring half-term swim short courses (Pre-School, Junior Beginners and Junior Improver levels) and all-day Junior Gym sessions at South Norwood Leisure Centre, run every school half term.",
    category: "Sports",
    borough: "Croydon",
    venue: "South Norwood Leisure Centre",
    address: "164 Portland Road, South Norwood, London SE25 4PT",
    lat: 51.3958,
    lng: -0.0794,
    ageMin: 4,
    ageMax: 11,
    isFree: false,
    priceMin: 6,
    priceMax: 10,
    startDate: "2026-10-19",
    endDate: "2026-10-23",
    times: "Weekdays, 9am-6pm (swim lessons 9am-12noon)",
    sourceName: "Better (GLL)",
    sourceUrl:
      "https://www.better.org.uk/leisure-centre/london/croydon/south-norwood-leisure-centre/half-term-south-norwood-leisure-centre",
  },
  {
    title: "Dinosaur Playground & Crystal Palace Dinosaurs",
    description:
      "A sensory-rich, accessible playground on the Dinosaur Park islands next to the restored Grade I-listed Victorian dinosaur sculptures, free to explore during normal park hours.",
    category: "Nature",
    borough: "Bromley",
    venue: "Crystal Palace Park",
    address: "Thicket Road, Penge, London SE20 8DT",
    lat: 51.4185561,
    lng: -0.0621988,
    ageMin: 2,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-24",
    endDate: "2026-09-06",
    times: "Open daily, 7:30am - 8:30pm (4:30pm in winter)",
    sourceName: "Crystal Palace Park Trust",
    sourceUrl:
      "https://www.crystalpalaceparktrust.org/pages/crystal-palace-park-dinosaur-playground-opens-march-2026",
  },
  {
    title: "Greenwich Fair – Greenwich+Docklands International Festival",
    description:
      "A free weekend of outdoor circus, dance and puppetry on the Grand Ascent in Greenwich Park, including the aerial spectacle 'ElevateHer' and street dance piece 'BUG', as part of GDIF.",
    category: "Music & Drama",
    borough: "Greenwich",
    venue: "Greenwich Park (Grand Ascent)",
    address: "Greenwich Park, London SE10 8XJ",
    lat: 51.4721658,
    lng: 0.0035489,
    ageMin: 0,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-22",
    endDate: "2026-08-23",
    times: "1pm - 6pm, unticketed",
    sourceName: "Time Out London",
    sourceUrl:
      "https://www.timeout.com/london/theatre/greenwich-and-docklands-international-festival",
  },
  {
    title: "Summer at Battersea Park Children's Zoo",
    description:
      "Meet meerkats, monkeys, wallabies and more at this small family zoo inside Battersea Park, with keeper talks and play areas included in admission.",
    category: "Nature",
    borough: "Wandsworth",
    venue: "Battersea Park Children's Zoo",
    address: "Battersea Park, Carriage Drive North, London SW11 4NJ",
    lat: 51.4811854,
    lng: -0.1565664,
    ageMin: 0,
    ageMax: 12,
    isFree: false,
    priceMin: 8.95,
    priceMax: 35.5,
    startDate: "2026-07-24",
    endDate: "2026-09-06",
    times: "Summer hours: daily 10am - 5:30pm (last entry 4:30pm)",
    sourceName: "Battersea Park Children's Zoo",
    sourceUrl: "https://www.batterseaparkzoo.co.uk/tickets/prices/",
  },
  {
    title: "Mini Explorers Drop-In Family Art Sessions",
    description:
      "Free drop-in art-making sessions for young children and their families, exploring the Gallery's collection through stories and hands-on making, part of the Summer Family Festival.",
    category: "Arts & Crafts",
    borough: "Southwark",
    venue: "Dulwich Picture Gallery",
    address: "Gallery Road, Dulwich Village, London SE21 7AD",
    lat: 51.4459604,
    lng: -0.0863251,
    ageMin: 2,
    ageMax: 8,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-21",
    endDate: "2026-08-25",
    times: "Drop-in, check gallery for daily session times",
    sourceName: "Dulwich Picture Gallery",
    sourceUrl:
      "https://www.dulwichpicturegallery.org.uk/whats-on/summer-family-festival-2/",
  },
];

async function main() {
  await prisma.activity.deleteMany();
  for (const activity of activities) {
    await prisma.activity.create({
      data: {
        ...activity,
        startDate: new Date(activity.startDate),
        endDate: new Date(activity.endDate),
      },
    });
  }
  console.log(`Seeded ${activities.length} activities.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
