import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL ?? "file:./dev.db",
});
const prisma = new PrismaClient({ adapter });

type Seed = {
  title: string;
  description: string;
  category: string;
  borough: string;
  venue: string;
  address: string;
  lat: number;
  lng: number;
  ageMin: number;
  ageMax: number;
  isFree: boolean;
  priceMin: number;
  priceMax: number;
  startDate: string;
  endDate: string;
  times?: string;
  sourceName: string;
  sourceUrl: string;
};

const activities: Seed[] = [
  {
    title: "Brockwell Park Summer Play Scheme",
    description:
      "Council-run holiday play scheme with den building, sports and arts and crafts in the park. Drop-in sessions, free to attend.",
    category: "Multi-activity Camp",
    borough: "Lambeth",
    venue: "Brockwell Park",
    address: "Dulwich Rd, London SE24 0PA",
    lat: 51.4508,
    lng: -0.1041,
    ageMin: 5,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-21",
    times: "Weekdays, 10am - 3pm",
    sourceName: "Lambeth Council",
    sourceUrl: "https://www.lambeth.gov.uk/holiday-activities",
  },
  {
    title: "Kennington Park Multi-Sports Camp",
    description:
      "Football, dodgeball and athletics coaching for school-age children, run by qualified coaches. HAF-funded places available for eligible families.",
    category: "Sports",
    borough: "Lambeth",
    venue: "Kennington Park",
    address: "Kennington Park Pl, London SE11 4AS",
    lat: 51.4869,
    lng: -0.1077,
    ageMin: 6,
    ageMax: 14,
    isFree: false,
    priceMin: 18,
    priceMax: 25,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times: "Weekdays, 9am - 4pm",
    sourceName: "Streatham & District Sports Club",
    sourceUrl: "https://www.sdsports.org.uk/holiday-camps",
  },
  {
    title: "Tate Modern Family Art Workshop",
    description:
      "Drop-in family workshop inspired by current exhibitions. Children experiment with printmaking and collage alongside a professional artist.",
    category: "Arts & Crafts",
    borough: "Southwark",
    venue: "Tate Modern",
    address: "Bankside, London SE1 9TG",
    lat: 51.5076,
    lng: -0.0994,
    ageMin: 4,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-03",
    endDate: "2026-08-07",
    times: "11am - 4pm, drop in",
    sourceName: "Tate",
    sourceUrl: "https://www.tate.org.uk/visit/tate-modern/family",
  },
  {
    title: "Dulwich Park Bike Club",
    description:
      "Learn-to-ride and confidence-building cycling sessions on the park's traffic-free tracks. Bikes and helmets provided for younger riders.",
    category: "Outdoors",
    borough: "Southwark",
    venue: "Dulwich Park",
    address: "College Rd, London SE21 7BQ",
    lat: 51.4457,
    lng: -0.0846,
    ageMin: 4,
    ageMax: 9,
    isFree: false,
    priceMin: 8,
    priceMax: 8,
    startDate: "2026-07-25",
    endDate: "2026-09-01",
    times: "Saturdays, 10am - 1pm",
    sourceName: "Southwark Cyclists",
    sourceUrl: "https://southwarkcyclists.org.uk/dulwich-park-cycling",
  },
  {
    title: "Battersea Park Adventure Playground",
    description:
      "Supervised adventure playground with zip wire, climbing structures and den-building area. Free entry, small charge for organised activity sessions.",
    category: "Outdoors",
    borough: "Wandsworth",
    venue: "Battersea Park",
    address: "Battersea Park, London SW11 4NJ",
    lat: 51.4791,
    lng: -0.1587,
    ageMin: 5,
    ageMax: 13,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-30",
    times: "Tue-Sun, 10am - 5:30pm",
    sourceName: "Wandsworth Council",
    sourceUrl: "https://www.wandsworth.gov.uk/parks/battersea-park",
  },
  {
    title: "Tooting Common Junior Tennis Camp",
    description:
      "LTA-accredited coaches run mini-tennis and junior camps across three age groups, with a match-play tournament on the final day.",
    category: "Sports",
    borough: "Wandsworth",
    venue: "Tooting Common Tennis Courts",
    address: "Dr Johnson Ave, London SW17 7RH",
    lat: 51.4308,
    lng: -0.1552,
    ageMin: 6,
    ageMax: 16,
    isFree: false,
    priceMin: 30,
    priceMax: 45,
    startDate: "2026-08-10",
    endDate: "2026-08-14",
    times: "Weekdays, 9:30am - 3:30pm",
    sourceName: "Będkowski Tennis Academy",
    sourceUrl: "https://www.lta.org.uk/find-venue/tooting-common",
  },
  {
    title: "Streatham Ice and Leisure Family Skate",
    description:
      "Off-peak family skating sessions with skate aids for beginners. Great rainy-day activity for a range of ages and abilities.",
    category: "Sports",
    borough: "Lambeth",
    venue: "Streatham Ice and Leisure Centre",
    address: "386 Streatham High Rd, London SW16 6HT",
    lat: 51.4204,
    lng: -0.1305,
    ageMin: 4,
    ageMax: 16,
    isFree: false,
    priceMin: 7,
    priceMax: 12,
    startDate: "2026-07-25",
    endDate: "2026-09-02",
    times: "Daily, sessions from 10am",
    sourceName: "Everyone Active",
    sourceUrl: "https://www.everyoneactive.com/centre/streatham-ice-and-leisure-centre/",
  },
  {
    title: "Crystal Palace Park Dinosaur Trail & Craft Day",
    description:
      "Self-guided trail around the Victorian dinosaur sculptures followed by a fossil-themed craft table hosted by park rangers.",
    category: "Outdoors",
    borough: "Bromley",
    venue: "Crystal Palace Park",
    address: "Thicket Rd, London SE20 8DT",
    lat: 51.4199,
    lng: -0.0688,
    ageMin: 4,
    ageMax: 10,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-04",
    endDate: "2026-08-04",
    times: "11am - 3pm",
    sourceName: "Crystal Palace Park Trust",
    sourceUrl: "https://crystalpalaceparktrust.org/events",
  },
  {
    title: "Bromley Central Library STEM Club",
    description:
      "Hands-on science and coding sessions using littleBits, micro:bits and simple robotics kits. Booking essential, small group sizes.",
    category: "STEM",
    borough: "Bromley",
    venue: "Bromley Central Library",
    address: "High St, Bromley BR1 1EX",
    lat: 51.4032,
    lng: 0.0148,
    ageMin: 8,
    ageMax: 13,
    isFree: false,
    priceMin: 5,
    priceMax: 5,
    startDate: "2026-08-11",
    endDate: "2026-08-13",
    times: "1pm - 3pm",
    sourceName: "Bromley Libraries",
    sourceUrl: "https://www.bromley.gov.uk/libraries/events",
  },
  {
    title: "Greenwich Park Junior Rangers",
    description:
      "Wildlife-spotting and conservation activity mornings with the Royal Parks rangers, including pond-dipping and mini-beast hunts.",
    category: "Outdoors",
    borough: "Greenwich",
    venue: "Greenwich Park",
    address: "Charlton Way, London SE10 8QY",
    lat: 51.4769,
    lng: -0.0005,
    ageMin: 5,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-08-01",
    times: "10am - 12pm",
    sourceName: "The Royal Parks",
    sourceUrl: "https://www.royalparks.org.uk/whats-on/greenwich-park",
  },
  {
    title: "National Maritime Museum Family Explorer Day",
    description:
      "Themed trails, storytelling sessions and a hands-on knot-tying workshop exploring the museum's galleries.",
    category: "Arts & Crafts",
    borough: "Greenwich",
    venue: "National Maritime Museum",
    address: "Romney Rd, London SE10 9NF",
    lat: 51.4816,
    lng: -0.0093,
    ageMin: 5,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-17",
    endDate: "2026-08-21",
    times: "10:30am - 4pm",
    sourceName: "Royal Museums Greenwich",
    sourceUrl: "https://www.rmg.co.uk/whats-on",
  },
  {
    title: "Ladywell Fields Multi-Sports & Games",
    description:
      "HAF-funded inclusive sports sessions covering football, cricket and athletics, with a free healthy lunch provided.",
    category: "Sports",
    borough: "Lewisham",
    venue: "Ladywell Fields",
    address: "Ladywell Rd, London SE13 7TY",
    lat: 51.4535,
    lng: -0.0155,
    ageMin: 5,
    ageMax: 14,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-14",
    times: "Weekdays, 9:30am - 2:30pm",
    sourceName: "Lewisham Council (HAF Programme)",
    sourceUrl: "https://lewisham.gov.uk/haf",
  },
  {
    title: "Horniman Museum Nature Detectives",
    description:
      "Explore the Horniman's gardens and natural history collection with a self-led detective trail and a live animal handling session.",
    category: "STEM",
    borough: "Lewisham",
    venue: "Horniman Museum and Gardens",
    address: "100 London Rd, Forest Hill, London SE23 3PQ",
    lat: 51.4392,
    lng: -0.0654,
    ageMin: 4,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-05",
    endDate: "2026-08-06",
    times: "10am - 5pm",
    sourceName: "Horniman Museum",
    sourceUrl: "https://www.horniman.ac.uk/whats-on",
  },
  {
    title: "Morden Hall Park Wild Play",
    description:
      "National Trust rangers lead bug hunts, willow weaving and river-dipping sessions along the Wandle in this riverside park.",
    category: "Outdoors",
    borough: "Merton",
    venue: "Morden Hall Park",
    address: "Morden Hall Rd, Morden SM4 5JD",
    lat: 51.4059,
    lng: -0.1938,
    ageMin: 4,
    ageMax: 10,
    isFree: false,
    priceMin: 6,
    priceMax: 6,
    startDate: "2026-08-05",
    endDate: "2026-08-05",
    times: "10am - 12:30pm",
    sourceName: "National Trust",
    sourceUrl: "https://www.nationaltrust.org.uk/visit/london/morden-hall-park",
  },
  {
    title: "Wimbledon Park Youth Sailing Taster",
    description:
      "Introductory sailing and paddleboarding sessions on Wimbledon Park Lake with qualified RYA instructors, all equipment supplied.",
    category: "Sports",
    borough: "Merton",
    venue: "Wimbledon Park Watersports Centre",
    address: "Home Park Rd, London SW19 7HX",
    lat: 51.4335,
    lng: -0.2107,
    ageMin: 8,
    ageMax: 16,
    isFree: false,
    priceMin: 20,
    priceMax: 20,
    startDate: "2026-08-17",
    endDate: "2026-08-21",
    times: "Weekdays, half-day sessions",
    sourceName: "Wimbledon Park Watersports Centre",
    sourceUrl: "https://www.wimbledonparkwatersports.co.uk",
  },
  {
    title: "Sutton Central Library Coding Club",
    description:
      "Beginner-friendly Scratch and micro:bit coding club run by library staff, with a showcase session for parents on the last day.",
    category: "STEM",
    borough: "Sutton",
    venue: "Sutton Central Library",
    address: "St Nicholas Way, Sutton SM1 1EA",
    lat: 51.3609,
    lng: -0.1926,
    ageMin: 8,
    ageMax: 13,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-10",
    endDate: "2026-08-13",
    times: "1pm - 3pm",
    sourceName: "Sutton Libraries",
    sourceUrl: "https://www.sutton.gov.uk/libraries/events",
  },
  {
    title: "Manor Park Multi-Activity Holiday Camp",
    description:
      "Full-day camp mixing sports, arts and team games for a broad age range, with early drop-off and late pick-up options.",
    category: "Multi-activity Camp",
    borough: "Sutton",
    venue: "Manor Park Sports Ground",
    address: "Rectory Rd, Sutton SM1 3AR",
    lat: 51.3663,
    lng: -0.1889,
    ageMin: 5,
    ageMax: 12,
    isFree: false,
    priceMin: 28,
    priceMax: 32,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times: "Weekdays, 8am - 6pm",
    sourceName: "Premier Education",
    sourceUrl: "https://www.premier-education.com/holiday-camps/sutton",
  },
  {
    title: "Kingston Riverside Family Canoe Session",
    description:
      "Guided canoe and kayak taster sessions on the Thames towpath, suitable for confident young paddlers and their parents.",
    category: "Sports",
    borough: "Kingston upon Thames",
    venue: "Kingston Canoe Club",
    address: "Lower Ham Rd, Kingston upon Thames KT2 5AU",
    lat: 51.4132,
    lng: -0.3054,
    ageMin: 8,
    ageMax: 16,
    isFree: false,
    priceMin: 15,
    priceMax: 15,
    startDate: "2026-08-01",
    endDate: "2026-08-30",
    times: "Saturdays, 10am - 12pm",
    sourceName: "Kingston Canoe Club",
    sourceUrl: "https://www.kingstoncanoeclub.co.uk",
  },
  {
    title: "Bushy Park Deer Trail & Craft Morning",
    description:
      "Guided walk to spot the park's famous red and fallow deer herds followed by a nature-craft session using natural materials.",
    category: "Outdoors",
    borough: "Kingston upon Thames",
    venue: "Bushy Park",
    address: "Hampton Court Rd, Hampton TW12 2EJ",
    lat: 51.4132,
    lng: -0.3389,
    ageMin: 4,
    ageMax: 10,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-12",
    endDate: "2026-08-12",
    times: "10am - 12pm",
    sourceName: "The Royal Parks",
    sourceUrl: "https://www.royalparks.org.uk/whats-on/bushy-park",
  },
  {
    title: "Richmond Park Young Naturalists Club",
    description:
      "Monthly-turned-holiday-special club for budding naturalists, including deer safety talks, tree identification and sketching.",
    category: "Outdoors",
    borough: "Richmond upon Thames",
    venue: "Richmond Park",
    address: "Holly Lodge, Richmond TW10 5HS",
    lat: 51.4452,
    lng: -0.2734,
    ageMin: 6,
    ageMax: 12,
    isFree: false,
    priceMin: 10,
    priceMax: 10,
    startDate: "2026-08-06",
    endDate: "2026-08-06",
    times: "10am - 1pm",
    sourceName: "Friends of Richmond Park",
    sourceUrl: "https://www.frp.org.uk/events",
  },
  {
    title: "Marble Hill Park Summer Music & Dance Days",
    description:
      "Drama, music and dance workshops culminating in a mini-showcase for family and friends on the final afternoon.",
    category: "Music & Dance",
    borough: "Richmond upon Thames",
    venue: "Marble Hill House Stable Yard",
    address: "Richmond Rd, Twickenham TW1 2NL",
    lat: 51.4503,
    lng: -0.3238,
    ageMin: 6,
    ageMax: 14,
    isFree: false,
    priceMin: 35,
    priceMax: 35,
    startDate: "2026-08-24",
    endDate: "2026-08-28",
    times: "Weekdays, 9:30am - 3pm",
    sourceName: "Chickenshed Richmond",
    sourceUrl: "https://www.chickenshed.org.uk/richmond-holiday-workshops",
  },
  {
    title: "Croydon Fairfield Halls Youth Drama Intensive",
    description:
      "A week-long drama intensive covering improvisation, voice and movement, ending with a short performance for family.",
    category: "Music & Dance",
    borough: "Croydon",
    venue: "Fairfield Halls",
    address: "Park Ln, Croydon CR9 1DG",
    lat: 51.3736,
    lng: -0.0972,
    ageMin: 9,
    ageMax: 16,
    isFree: false,
    priceMin: 40,
    priceMax: 40,
    startDate: "2026-08-17",
    endDate: "2026-08-21",
    times: "Weekdays, 10am - 4pm",
    sourceName: "Fairfield Halls",
    sourceUrl: "https://www.fairfield.co.uk/whats-on/family",
  },
  {
    title: "Croydon Central Library Summer Reading Challenge Party",
    description:
      "Kick-off party for the Summer Reading Challenge with storytelling, a book swap table and craft activities. Free, no booking needed.",
    category: "Arts & Crafts",
    borough: "Croydon",
    venue: "Croydon Central Library",
    address: "Katharine St, Croydon CR9 1ET",
    lat: 51.3717,
    lng: -0.0982,
    ageMin: 4,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-25",
    endDate: "2026-07-25",
    times: "10:30am - 1pm",
    sourceName: "Croydon Libraries",
    sourceUrl: "https://www.croydon.gov.uk/libraries/summer-reading-challenge",
  },
  {
    title: "Selhurst Park Junior Football Skills Camp",
    description:
      "Official club-badged football skills camp with small-sided games and a stadium tour on the final day.",
    category: "Sports",
    borough: "Croydon",
    venue: "Crystal Palace FC Training Ground",
    address: "Copers Cope Rd, Beckenham BR3 1NZ",
    lat: 51.4128,
    lng: -0.0296,
    ageMin: 6,
    ageMax: 14,
    isFree: false,
    priceMin: 32,
    priceMax: 38,
    startDate: "2026-08-03",
    endDate: "2026-08-07",
    times: "Weekdays, 9am - 3pm",
    sourceName: "Crystal Palace FC Foundation",
    sourceUrl: "https://www.cpfc.co.uk/foundation/holiday-camps",
  },
  {
    title: "Beckenham Place Park Forest School",
    description:
      "Woodland forest-school sessions with fire lighting (supervised), shelter building and tool use appropriate to age group.",
    category: "Outdoors",
    borough: "Bromley",
    venue: "Beckenham Place Park",
    address: "Beckenham Hill Rd, Beckenham BR3 2BP",
    lat: 51.4225,
    lng: -0.0201,
    ageMin: 6,
    ageMax: 12,
    isFree: false,
    priceMin: 22,
    priceMax: 22,
    startDate: "2026-08-10",
    endDate: "2026-08-12",
    times: "9:30am - 3:30pm",
    sourceName: "Kids Forest School CIC",
    sourceUrl: "https://kidsforestschool.co.uk/beckenham-place-park",
  },
  {
    title: "Half Term: Horniman Halloween Explorers",
    description:
      "October half-term special exploring the museum's natural history collection with a lantern-making craft session.",
    category: "Arts & Crafts",
    borough: "Lewisham",
    venue: "Horniman Museum and Gardens",
    address: "100 London Rd, Forest Hill, London SE23 3PQ",
    lat: 51.4392,
    lng: -0.0654,
    ageMin: 5,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-10-26",
    endDate: "2026-10-30",
    times: "10am - 4pm",
    sourceName: "Horniman Museum",
    sourceUrl: "https://www.horniman.ac.uk/whats-on",
  },
  {
    title: "Half Term: Battersea Power Station Junior Robotics",
    description:
      "Introduction to robotics using LEGO Spike kits, culminating in a small robot-racing challenge. Booking required.",
    category: "STEM",
    borough: "Wandsworth",
    venue: "Battersea Power Station",
    address: "188 Kirtling St, London SW11 8BZ",
    lat: 51.4816,
    lng: -0.1436,
    ageMin: 7,
    ageMax: 13,
    isFree: false,
    priceMin: 18,
    priceMax: 18,
    startDate: "2026-10-27",
    endDate: "2026-10-29",
    times: "11am - 1pm",
    sourceName: "Kids Tech Club",
    sourceUrl: "https://www.kidstechclub.co.uk/battersea",
  },
  {
    title: "Half Term: Crystal Palace Park Pumpkin Trail",
    description:
      "Family-friendly pumpkin trail through the park with a craft tent and a short talk from the park rangers.",
    category: "Outdoors",
    borough: "Bromley",
    venue: "Crystal Palace Park",
    address: "Thicket Rd, London SE20 8DT",
    lat: 51.4199,
    lng: -0.0688,
    ageMin: 4,
    ageMax: 10,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-10-26",
    endDate: "2026-10-31",
    times: "10am - 4pm",
    sourceName: "Crystal Palace Park Trust",
    sourceUrl: "https://crystalpalaceparktrust.org/events",
  },
  {
    title: "Half Term: Greenwich Peninsula Ecology Park Sessions",
    description:
      "Pond-dipping and mini-beast hunting at the ecology park's wetland habitat, run by local conservation volunteers.",
    category: "Outdoors",
    borough: "Greenwich",
    venue: "Greenwich Peninsula Ecology Park",
    address: "John Harrison Way, London SE10 0QZ",
    lat: 51.5029,
    lng: 0.0075,
    ageMin: 4,
    ageMax: 11,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-10-27",
    endDate: "2026-10-28",
    times: "10:30am - 12:30pm",
    sourceName: "Trust for Urban Ecology",
    sourceUrl: "https://www.greenwichpeninsulaecologypark.org",
  },
  {
    title: "Wandsworth Common Junior Athletics Camp",
    description:
      "Track and field skills camp run by qualified England Athletics coaches, grouped by age for age-appropriate coaching.",
    category: "Sports",
    borough: "Wandsworth",
    venue: "Wandsworth Common Athletics Track",
    address: "Dorlcote Rd, London SW18 3RT",
    lat: 51.4482,
    lng: -0.1673,
    ageMin: 7,
    ageMax: 15,
    isFree: false,
    priceMin: 24,
    priceMax: 24,
    startDate: "2026-08-24",
    endDate: "2026-08-28",
    times: "Weekdays, 9am - 3pm",
    sourceName: "Wandsworth Athletics Club",
    sourceUrl: "https://www.wandsworthac.org/holiday-camps",
  },
  {
    title: "Peckham Rye Park Teen Skate & BMX Sessions",
    description:
      "Supervised sessions at the skate park with coaching taster slots for beginners, aimed at older kids and young teens.",
    category: "Sports",
    borough: "Southwark",
    venue: "Peckham Rye Park Skate Park",
    address: "Peckham Rye, London SE15 3UA",
    lat: 51.4655,
    lng: -0.0700,
    ageMin: 10,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times: "Weekday afternoons, 3pm - 6pm",
    sourceName: "Southwark Council",
    sourceUrl: "https://www.southwark.gov.uk/parks-and-green-spaces/peckham-rye-park",
  },
  {
    title: "South Norwood Country Park Bushcraft for Teens",
    description:
      "Bushcraft skills for older children including fire lighting, shelter building and basic navigation, run over three days.",
    category: "Outdoors",
    borough: "Croydon",
    venue: "South Norwood Country Park",
    address: "Albert Rd, London SE25 4QL",
    lat: 51.3963,
    lng: -0.0755,
    ageMin: 11,
    ageMax: 16,
    isFree: false,
    priceMin: 45,
    priceMax: 45,
    startDate: "2026-08-18",
    endDate: "2026-08-20",
    times: "9am - 4pm",
    sourceName: "Bear Grylls Survival Academy",
    sourceUrl: "https://beargryllssurvivalacademy.com/south-norwood",
  },
  {
    title: "Vauxhall City Farm Animal Care Days",
    description:
      "Hands-on animal care sessions helping to feed and groom the farm's goats, ponies and poultry, with a short talk on animal welfare.",
    category: "Outdoors",
    borough: "Lambeth",
    venue: "Vauxhall City Farm",
    address: "165 Tyers St, London SE11 5HS",
    lat: 51.4874,
    lng: -0.1226,
    ageMin: 4,
    ageMax: 10,
    isFree: false,
    priceMin: 6,
    priceMax: 6,
    startDate: "2026-08-04",
    endDate: "2026-08-28",
    times: "Tuesdays & Thursdays, 11am - 1pm",
    sourceName: "Vauxhall City Farm",
    sourceUrl: "https://vauxhallcityfarm.org/whats-on",
  },
  {
    title: "Clapham Common Skate Park Beginners Sessions",
    description:
      "Free coached beginner skateboarding sessions with boards available to borrow, run by local skate club volunteers.",
    category: "Sports",
    borough: "Lambeth",
    venue: "Clapham Common Skate Park",
    address: "Clapham Common South Side, London SW4 9BN",
    lat: 51.4618,
    lng: -0.1495,
    ageMin: 8,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-28",
    endDate: "2026-08-25",
    times: "Tuesdays, 4pm - 6pm",
    sourceName: "Lambeth Council",
    sourceUrl: "https://www.lambeth.gov.uk/parks/clapham-common",
  },
  {
    title: "Southbank Centre Family Music Lab",
    description:
      "Interactive music-making workshop with percussion instruments and looping pedals, no experience needed, followed by a short performance.",
    category: "Music & Dance",
    borough: "Southwark",
    venue: "Southbank Centre",
    address: "Belvedere Rd, London SE1 8XX",
    lat: 51.5055,
    lng: -0.1170,
    ageMin: 5,
    ageMax: 12,
    isFree: false,
    priceMin: 10,
    priceMax: 10,
    startDate: "2026-08-11",
    endDate: "2026-08-12",
    times: "11am - 12:30pm",
    sourceName: "Southbank Centre",
    sourceUrl: "https://www.southbankcentre.co.uk/whats-on/family",
  },
  {
    title: "Herne Hill Velodrome Junior Cycling Camp",
    description:
      "Track cycling taster camp for confident young riders, with British Cycling qualified coaches and bikes available to hire.",
    category: "Sports",
    borough: "Lambeth",
    venue: "Herne Hill Velodrome",
    address: "104 Burbage Rd, London SE24 9HE",
    lat: 51.4508,
    lng: -0.1004,
    ageMin: 9,
    ageMax: 16,
    isFree: false,
    priceMin: 25,
    priceMax: 25,
    startDate: "2026-08-03",
    endDate: "2026-08-05",
    times: "9:30am - 12:30pm",
    sourceName: "Herne Hill Velodrome Trust",
    sourceUrl: "https://www.hernehillvelodrome.com/junior-camps",
  },
  {
    title: "Burgess Park Teen Basketball League",
    description:
      "Drop-in 3-on-3 basketball league for teens with a coach on hand, running across the summer with a finals day in the last week.",
    category: "Sports",
    borough: "Southwark",
    venue: "Burgess Park Basketball Courts",
    address: "Albany Rd, London SE5 0AL",
    lat: 51.4823,
    lng: -0.0836,
    ageMin: 12,
    ageMax: 16,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times: "Weekday evenings, 5pm - 7pm",
    sourceName: "Southwark Council",
    sourceUrl: "https://www.southwark.gov.uk/parks-and-green-spaces/burgess-park",
  },
  {
    title: "Wandsworth Museum Young Historians Workshop",
    description:
      "Hands-on history workshop with replica artefacts and a local-history trail around old Wandsworth, aimed at curious older children.",
    category: "Arts & Crafts",
    borough: "Wandsworth",
    venue: "Wandsworth Museum",
    address: "Garratt Ln, London SW18 4AQ",
    lat: 51.4568,
    lng: -0.1926,
    ageMin: 8,
    ageMax: 13,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-19",
    endDate: "2026-08-20",
    times: "11am - 1pm",
    sourceName: "Wandsworth Heritage Service",
    sourceUrl: "https://www.wandsworth.gov.uk/museum",
  },
  {
    title: "Alexandra Recreation Ground Pop-Up Playscheme",
    description:
      "Free drop-in play scheme with sports equipment, giant games and a bouncy castle on Fridays, run by the council's play team.",
    category: "Multi-activity Camp",
    borough: "Croydon",
    venue: "Alexandra Recreation Ground",
    address: "Bensham Ln, Thornton Heath CR7 7AF",
    lat: 51.3985,
    lng: -0.1097,
    ageMin: 4,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-07-27",
    endDate: "2026-08-28",
    times: "Fridays, 11am - 3pm",
    sourceName: "Croydon Council",
    sourceUrl: "https://www.croydon.gov.uk/parks/holiday-play",
  },
  {
    title: "Danson Park Teen Watersports Week",
    description:
      "Kayaking, raft-building and stand-up paddleboarding on the lake, aimed at older kids wanting a more independent activity week.",
    category: "Sports",
    borough: "Bromley",
    venue: "Danson Watersports Centre",
    address: "Danson Park, Bexleyheath DA6 8HL",
    lat: 51.4570,
    lng: 0.1303,
    ageMin: 11,
    ageMax: 16,
    isFree: false,
    priceMin: 38,
    priceMax: 38,
    startDate: "2026-08-24",
    endDate: "2026-08-28",
    times: "Weekdays, 10am - 3pm",
    sourceName: "Danson Watersports Centre",
    sourceUrl: "https://www.dansonwatersports.co.uk",
  },
  {
    title: "Eltham Palace Tudor Explorers Day",
    description:
      "Costumed guided tour of the medieval palace and Art Deco house, followed by a Tudor-craft session making wax seals and quills.",
    category: "Arts & Crafts",
    borough: "Greenwich",
    venue: "Eltham Palace and Gardens",
    address: "Court Yard, London SE9 5QE",
    lat: 51.4525,
    lng: 0.0511,
    ageMin: 5,
    ageMax: 11,
    isFree: false,
    priceMin: 14,
    priceMax: 14,
    startDate: "2026-08-13",
    endDate: "2026-08-13",
    times: "10:30am - 2:30pm",
    sourceName: "English Heritage",
    sourceUrl: "https://www.english-heritage.org.uk/visit/places/eltham-palace-and-gardens",
  },
  {
    title: "Mountsfield Park Junior Parkour Taster",
    description:
      "Introductory parkour and freerunning session with qualified coaches, focusing on balance, vaulting and safe landings.",
    category: "Sports",
    borough: "Lewisham",
    venue: "Mountsfield Park",
    address: "Stainton Rd, London SE6 1PQ",
    lat: 51.4453,
    lng: -0.0184,
    ageMin: 8,
    ageMax: 15,
    isFree: false,
    priceMin: 12,
    priceMax: 12,
    startDate: "2026-08-05",
    endDate: "2026-08-05",
    times: "2pm - 3:30pm",
    sourceName: "Parkour Generations",
    sourceUrl: "https://parkourgenerations.com/lewisham-holiday-sessions",
  },
  {
    title: "Morden Park Family Fun Day",
    description:
      "Free community fun day with inflatables, a mini fun-fair, face painting and local sports club taster stalls.",
    category: "Multi-activity Camp",
    borough: "Merton",
    venue: "Morden Park",
    address: "London Rd, Morden SM4 5QU",
    lat: 51.3899,
    lng: -0.1994,
    ageMin: 4,
    ageMax: 12,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-08",
    endDate: "2026-08-08",
    times: "11am - 4pm",
    sourceName: "Merton Council",
    sourceUrl: "https://www.merton.gov.uk/parks/morden-park",
  },
  {
    title: "Rose Theatre Kingston Youth Drama Week",
    description:
      "Full-day drama workshops for teens exploring devising and script work, with a shared performance for family on the final evening.",
    category: "Music & Dance",
    borough: "Kingston upon Thames",
    venue: "Rose Theatre Kingston",
    address: "24-26 High St, Kingston upon Thames KT1 1HL",
    lat: 51.4113,
    lng: -0.3020,
    ageMin: 12,
    ageMax: 16,
    isFree: false,
    priceMin: 42,
    priceMax: 42,
    startDate: "2026-08-17",
    endDate: "2026-08-21",
    times: "Weekdays, 10am - 4pm",
    sourceName: "Rose Theatre Kingston",
    sourceUrl: "https://www.rosetheatrekingston.org/whats-on/youth-drama",
  },
  {
    title: "Ham Lands Nature Reserve Bug Safari",
    description:
      "Guided bug and pond-life safari along the Thames-side nature reserve, with magnifying pots and identification sheets provided.",
    category: "Outdoors",
    borough: "Richmond upon Thames",
    venue: "Ham Lands Nature Reserve",
    address: "Riverside Dr, Ham, Richmond TW10 7QB",
    lat: 51.4370,
    lng: -0.3053,
    ageMin: 4,
    ageMax: 9,
    isFree: true,
    priceMin: 0,
    priceMax: 0,
    startDate: "2026-08-10",
    endDate: "2026-08-10",
    times: "10am - 11:30am",
    sourceName: "London Wildlife Trust",
    sourceUrl: "https://www.wildlondon.org.uk/nature-reserves/ham-lands",
  },
  {
    title: "Sutton Green Gym Junior Fitness Camp",
    description:
      "Circuit-style fitness sessions adapted for children, mixing games with basic strength and conditioning exercises.",
    category: "Sports",
    borough: "Sutton",
    venue: "Sutton Green Gym",
    address: "Rosehill Park, Sutton SM1 3RB",
    lat: 51.3684,
    lng: -0.1789,
    ageMin: 9,
    ageMax: 15,
    isFree: false,
    priceMin: 16,
    priceMax: 16,
    startDate: "2026-07-29",
    endDate: "2026-08-26",
    times: "Wednesdays, 4pm - 5pm",
    sourceName: "Sutton Council",
    sourceUrl: "https://www.sutton.gov.uk/leisure/junior-fitness",
  },
  {
    title: "Half Term: Fairfield Halls Family Panto Workshop",
    description:
      "A playful introduction to pantomime performance skills ahead of the Christmas season, with silly walks, songs and a scene showcase.",
    category: "Music & Dance",
    borough: "Croydon",
    venue: "Fairfield Halls",
    address: "Park Ln, Croydon CR9 1DG",
    lat: 51.3736,
    lng: -0.0972,
    ageMin: 6,
    ageMax: 12,
    isFree: false,
    priceMin: 15,
    priceMax: 15,
    startDate: "2026-10-28",
    endDate: "2026-10-29",
    times: "10am - 12:30pm",
    sourceName: "Fairfield Halls",
    sourceUrl: "https://www.fairfield.co.uk/whats-on/family",
  },
];

async function main() {
  await prisma.activity.deleteMany();
  for (const activity of activities) {
    await prisma.activity.create({
      data: {
        ...activity,
        startDate: new Date(activity.startDate),
        endDate: new Date(activity.endDate),
      },
    });
  }
  console.log(`Seeded ${activities.length} activities.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
